// Generated by Haxe 3.4.2
package haxe.lang;

@SuppressWarnings(value={"rawtypes"})
public class Closure extends haxe.lang.VarArgsBase
{
	public Closure(java.lang.Object obj, java.lang.String field)
	{
		super(-1, -1);
		this.obj = obj;
		this.field = field;
	}
	
	
	public java.lang.Object obj;
	
	public java.lang.String field;
	
	@Override public java.lang.Object __hx_invokeDynamic(haxe.root.Array dynArgs)
	{
		return haxe.lang.Runtime.callField(this.obj, this.field, dynArgs);
	}
	
	
	@Override public boolean equals(java.lang.Object obj)
	{
		if (( obj == null )) 
		{
			return false;
		}
		
		haxe.lang.Closure c = ((haxe.lang.Closure) (obj) );
		if (haxe.lang.Runtime.eq(c.obj, this.obj)) 
		{
			return haxe.lang.Runtime.valEq(c.field, this.field);
		}
		else
		{
			return false;
		}
		
	}
	
	
	@Override public int hashCode()
	{
		return ( Runtime.toInt(this.obj.hashCode()) ^ this.field.hashCode());
	}
	
	
}


