// Generated by Haxe 3.4.2
package haxe.lang;

public class Enum
{
	public Enum(int index)
	{
		this.index = index;
	}
	
	
	public final int index;
	
	public java.lang.String getTag()
	{
		throw haxe.lang.HaxeException.wrap("Not Implemented");
	}
	
	
	public haxe.root.Array<java.lang.Object> getParams()
	{
		return new haxe.root.Array<java.lang.Object>(new java.lang.Object[]{});
	}
	
	
	@Override public java.lang.String toString()
	{
		return this.getTag();
	}
	
	
}


