// Generated by Haxe 3.4.2
package haxe.lang;

import java.io.Serializable;

public class HaxeException extends java.lang.RuntimeException implements Serializable
{
	public static final long serialVersionUID = 5956463319488556322L;

	public HaxeException(java.lang.Object obj, java.lang.String msg, java.lang.Throwable cause)
	{
		super(msg, cause);
		if (( obj instanceof haxe.lang.HaxeException )) 
		{
			haxe.lang.HaxeException _obj = ((haxe.lang.HaxeException) (obj) );
			obj = _obj.getObject();
		}
		
		this.obj = obj;
	}
	
	
	public static java.lang.RuntimeException wrap(java.lang.Object obj)
	{
		java.lang.RuntimeException ret;
		if (( obj instanceof java.lang.RuntimeException )) 
		{
			ret = ((java.lang.RuntimeException) (obj) );
		}
		else
		{
			if (( obj instanceof java.lang.String )) 
			{
				ret = new haxe.lang.HaxeException(obj, haxe.lang.Runtime.toString(obj), null);
			}
			else
			{
				if (( obj instanceof java.lang.Throwable )) 
				{
					ret = new haxe.lang.HaxeException(obj, haxe.root.Std.string(obj), ((java.lang.Throwable) (obj) ));
				}
				else
				{
					ret = new haxe.lang.HaxeException(obj, haxe.root.Std.string(obj), null);
				}
				
			}
			
		}
		
		return ret;
	}
	
	
	public java.lang.Object obj;
	
	public java.lang.Object getObject()
	{
		return this.obj;
	}
	
	
	@Override public java.lang.Throwable fillInStackTrace()
	{
		return this;
	}
	
	
	@Override public java.lang.String toString()
	{
		return ( "Haxe Exception: " + haxe.root.Std.string(this.obj) );
	}
	
	
	@Override public java.lang.String getMessage()
	{
		java.lang.String _g = super.getMessage();
		if (( _g == null )) 
		{
			return haxe.root.Std.string(this.obj);
		}
		else
		{
			return _g;
		}
		
	}
	
	
}


