// Generated by Haxe 3.4.2
package haxe.lang;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class ParamEnum extends haxe.lang.Enum
{
	public ParamEnum(int index, java.lang.Object[] params)
	{
		super(index);
		this.params = params;
	}
	
	
	public final java.lang.Object[] params;
	
	@Override public haxe.root.Array<java.lang.Object> getParams()
	{
		if (( this.params == null )) 
		{
			return new haxe.root.Array<java.lang.Object>(new java.lang.Object[]{});
		}
		else
		{
			java.lang.Object[] this1 = this.params;
			haxe.root.Array a = new haxe.root.Array();
			int len = this1.length;
			{
				int _g1 = 0;
				while (( _g1 < len))
				{
					int i = _g1++;
					a.__set(i, ((Object[]) (this1) )[i]);
				}
				
			}
			
			return ((haxe.root.Array<java.lang.Object>) (a) );
		}
		
	}
	
	
	@Override public java.lang.String toString()
	{
		if (( ( this.params == null ) || ( this.params.length == 0 ) ))
		{
			return this.getTag();
		}
		
		haxe.root.StringBuf ret = new haxe.root.StringBuf();
		ret.add(haxe.lang.Runtime.toString(this.getTag()));
		ret.add(haxe.lang.Runtime.toString("("));
		boolean first = true;
		{
			int _g = 0;
			java.lang.Object[] _g1 = this.params;
			while (( _g < _g1.length ))
			{
				java.lang.Object p = ((Object[]) (_g1) )[_g];
				 ++ _g;
				if (first) 
				{
					first = false;
				}
				else
				{
					ret.add(haxe.lang.Runtime.toString(","));
				}
				
				ret.add(p);
			}
			
		}
		
		ret.add(haxe.lang.Runtime.toString(")"));
		return ret.toString();
	}
	
	
	@Override public boolean equals(java.lang.Object obj)
	{
		if (haxe.lang.Runtime.eq(obj, this)) 
		{
			return true;
		}
		
		haxe.lang.ParamEnum obj1 = ( (( obj instanceof haxe.lang.ParamEnum )) ? (((haxe.lang.ParamEnum) (obj) )) : (null) );
		boolean ret = ( ( ( obj1 != null ) && haxe.root.Std.is(obj1, haxe.root.Type.getEnum(this)) ) && ( obj1.index == this.index ) );
		if ( ! (ret) ) 
		{
			return false;
		}
		
		if (( obj1.params == this.params )) 
		{
			return true;
		}
		
		int len = 0;
		boolean tmp;
		if ( ! ((( ( obj1.params == null ) || ( this.params == null ) ))) ) 
		{
			len = this.params.length;
			tmp = ( len != obj1.params.length );
		}
		else
		{
			tmp = true;
		}
		
		if (tmp) 
		{
			return false;
		}
		
		{
			int _g1 = 0;
			while (( _g1 < len))
			{
				int i = _g1++;
				if ( ! (((boolean) (haxe.root.Type.enumEq(((Object[]) (obj1.params) )[i], ((Object[]) (this.params) )[i])) )) )
				{
					return false;
				}
				
			}
			
		}
		
		return true;
	}
	
	
	@Override public int hashCode()
	{
		int h = 19;
		if (( this.params != null )) 
		{
			int _g = 0;
			java.lang.Object[] _g1 = this.params;
			while (( _g < _g1.length ))
			{
				java.lang.Object p = ((Object[]) (_g1) )[_g];
				 ++ _g;
				h *= 31;
				if (( ! (( p == null )) )) 
				{
					h = Runtime.toInt(Runtime.plus(h, p.hashCode()));
				}
				
			}
			
		}
		
		h += this.index;
		return h;
	}
	
	
}


