// Generated by Haxe 3.4.2
package haxe.lang;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class StringRefl
{
	static
	{
		haxe.lang.StringRefl.fields = new haxe.root.Array<java.lang.String>(new java.lang.String[]{"length", "toUpperCase", "toLowerCase", "charAt", "charCodeAt", "indexOf", "lastIndexOf", "split", "substr", "substring"});
	}
	
	public StringRefl()
	{
	}
	
	
	public static haxe.root.Array<java.lang.String> fields;
	
	public static java.lang.Object handleGetField(java.lang.String str, java.lang.String f, boolean throwErrors)
	{
		{
			int __temp_hash3 = (f).hashCode();
			boolean __temp_executeDef2 = true;
			switch (__temp_hash3)
			{
				case -1106363674:
				{
					if ((f).equals("length"))
					{
						return str.length();
					}
					
					break;
				}
				
				
				case -399551817:
				case -1137582698:
				case 530542161:
				case -891529231:
				case 109648666:
				case -467511597:
				case 1943291465:
				case 397153782:
				case -1361633751:
				{
					if (( (( ( __temp_hash3 == -399551817 ) && (f).equals("toUpperCase") )) || ( (( ( __temp_hash3 == -1137582698 ) && (f).equals("toLowerCase") )) || ( (( ( __temp_hash3 == 530542161 ) && (f).equals("substring") )) || ( (( ( __temp_hash3 == -891529231 ) && (f).equals("substr") )) || ( (( ( __temp_hash3 == 109648666 ) && (f).equals("split") )) || ( (( ( __temp_hash3 == -467511597 ) && (f).equals("lastIndexOf") )) || ( (( ( __temp_hash3 == 1943291465 ) && (f).equals("indexOf") )) || ( (( ( __temp_hash3 == 397153782 ) && (f).equals("charCodeAt") )) || (f).equals("charAt") ) ) ) ) ) ) ) ))
					{
						return new haxe.lang.Closure(str, f);
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef2) 
			{
				if (throwErrors) 
				{
					throw haxe.lang.HaxeException.wrap(( ( "Field not found: \'" + f ) + "\' in String" ));
				}
				else
				{
					return null;
				}
				
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	public static java.lang.Object handleCallField(java.lang.String str, java.lang.String f, haxe.root.Array args)
	{
		haxe.root.Array _args = new haxe.root.Array(new java.lang.Object[]{str});
		if (( args == null )) 
		{
			args = _args;
		}
		else
		{
			args = _args.concat(args);
		}
		
		return haxe.lang.Runtime.slowCallField(haxe.lang.StringExt.class, f, args);
	}
	
	
}


