// Generated by Haxe 3.4.2
package haxe.lang;

@SuppressWarnings(value={"rawtypes"})
public class VarArgsFunction extends haxe.lang.VarArgsBase
{
	public VarArgsFunction(haxe.lang.Function fun)
	{
		super(-1, -1);
		this.fun = fun;
	}
	
	
	public haxe.lang.Function fun;
	
	@Override public java.lang.Object __hx_invokeDynamic(haxe.root.Array dynArgs)
	{
		return this.fun.__hx_invoke1_o(0.0, dynArgs);
	}
	
	
}


