// Generated by Haxe 3.4.2
package haxe.root;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public final class Array<T> extends haxe.lang.HxObject
{
	
	public Array(T[] _native)
	{
		this.__a = _native;
		this.length = _native.length;
	}
	public Array(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Array()
	{
		haxe.root.Array.__hx_ctor__Array(this);
	}
	
	
	public static <T_c> void __hx_ctor__Array(haxe.root.Array<T_c> __hx_this)
	{
		__hx_this.length = 0;
		__hx_this.__a = ((T_c[]) new Object[0]);
	}
	
	
	public static <X> haxe.root.Array<X> ofNative(X[] _native)
	{
		
			return new Array<X>(_native);
	
	}
	
	
	public static <Y> haxe.root.Array<Y> alloc(int size)
	{
		
			return new Array<Y>((Y[]) new Object[size]);
	
	}
	
	
	public int length;
	
	public T[] __a;
	
	public haxe.root.Array<T> concat(haxe.root.Array<T> a)
	{
		int length = this.length;
		int len = ( length + a.length );
		T[] retarr = ((T[]) new Object[len]);
		java.lang.System.arraycopy(this.__a, 0, retarr, 0, length);
		java.lang.System.arraycopy(a.__a, 0, retarr, length, a.length);
		return Array.ofNative(retarr);
	}
	
	
	public void concatNative(T[] a)
	{
		T[] __a = this.__a;
		int length = this.length;
		int len = ( length + a.length );
		if (( __a.length >= len )) 
		{
			java.lang.System.arraycopy(a, 0, __a, length, length);
		}
		else
		{
			T[] newarr = ((T[]) new Object[len]);
			java.lang.System.arraycopy(__a, 0, newarr, 0, length);
			java.lang.System.arraycopy(a, 0, newarr, length, a.length);
			this.__a = newarr;
		}
		
		this.length = len;
	}
	
	
	public java.lang.String join(java.lang.String sep)
	{
		haxe.root.StringBuf buf = new haxe.root.StringBuf();
		int i = -1;
		boolean first = true;
		int length = this.length;
		while ((  ++ i < length ))
		{
			if (first) 
			{
				first = false;
			}
			else
			{
				buf.add(haxe.lang.Runtime.toString(sep));
			}
			
			buf.add(this.__a[i]);
		}
		
		return buf.toString();
	}
	
	
	public java.lang.Object pop()
	{
		T[] __a = this.__a;
		int length = this.length;
		if (( length > 0 )) 
		{
			T val = __a[ -- length];
			__a[length] = null;
			this.length = length;
			return val;
		}
		else
		{
			return null;
		}
		
	}
	
	
	public int push(T x)
	{
		int length = this.length;
		if (( length >= this.__a.length )) 
		{
			int newLen = ( (( length << 1 )) + 1 );
			T[] newarr = ((T[]) new Object[newLen]);
			java.lang.System.arraycopy(this.__a, 0, newarr, 0, this.__a.length);
			this.__a = newarr;
		}
		
		this.__a[length] = x;
		return  ++ this.length;
	}
	
	
	public void reverse()
	{
		int i = 0;
		int l = this.length;
		T[] a = this.__a;
		int half = ( l >> 1 );
		 -- l;
		while (( i < half ))
		{
			T tmp = a[i];
			a[i] = a[( l - i )];
			a[( l - i )] = tmp;
			 ++ i;
		}
		
	}
	
	
	public java.lang.Object shift()
	{
		int l = this.length;
		if (( l == 0 )) 
		{
			return null;
		}
		
		T[] a = this.__a;
		T x = a[0];
		 -- l;
		java.lang.System.arraycopy(a, 1, a, 0, ( this.length - 1 ));
		a[l] = null;
		this.length = l;
		return x;
	}
	
	
	public haxe.root.Array<T> slice(int pos, java.lang.Object end)
	{
		if (( pos < 0 )) 
		{
			pos = ( this.length + pos );
			if (( pos < 0 )) 
			{
				pos = 0;
			}
			
		}
		
		if (haxe.lang.Runtime.eq(end, null)) 
		{
			end = this.length;
		}
		else
		{
			if (( haxe.lang.Runtime.compare(end, 0) < 0 )) 
			{
				end = haxe.lang.Runtime.toInt(haxe.lang.Runtime.plus(this.length, end));
			}
			
		}
		
		if (( haxe.lang.Runtime.compare(end, this.length) > 0 )) 
		{
			end = this.length;
		}
		
		int len = ( haxe.lang.Runtime.toInt(end) - pos);
		if (( len < 0 )) 
		{
			return new haxe.root.Array<T>();
		}
		
		T[] newarr = ((T[]) new Object[len]);
		java.lang.System.arraycopy(this.__a, pos, newarr, 0, len);
		return Array.ofNative(newarr);
	}
	
	
	public void sort(haxe.lang.Function f)
	{
		if (( this.length == 0 )) 
		{
			return ;
		}
		
		this.quicksort(0, ( this.length - 1 ), f);
	}
	
	
	public void quicksort(int lo, int hi, haxe.lang.Function f)
	{
		T[] buf = this.__a;
		int i = lo;
		int j = hi;
		T p = buf[( ( i + j ) >> 1 )];
		while (( i <= j ))
		{
			while (( ( i < hi ) && ( ((int) (f.__hx_invoke2_f(0.0, buf[i], 0.0, p)) ) < 0 ) ))
			{
				 ++ i;
			}
			
			while (( ( j > lo ) && ( ((int) (f.__hx_invoke2_f(0.0, buf[j], 0.0, p)) ) > 0 ) ))
			{
				 -- j;
			}
			
			if (( i <= j )) 
			{
				T t = buf[i];
				buf[i++] = buf[j];
				buf[j--] = t;
			}
			
		}
		
		if (( lo < j )) 
		{
			this.quicksort(lo, j, f);
		}
		
		if (( i < hi )) 
		{
			this.quicksort(i, hi, f);
		}
		
	}
	
	
	public haxe.root.Array<T> splice(int pos, int len)
	{
		if (( len < 0 )) 
		{
			return new haxe.root.Array<T>();
		}
		
		if (( pos < 0 )) 
		{
			pos = ( this.length + pos );
			if (( pos < 0 )) 
			{
				pos = 0;
			}
			
		}
		
		if (( pos > this.length )) 
		{
			pos = 0;
			len = 0;
		}
		else
		{
			if (( ( pos + len ) > this.length )) 
			{
				len = ( this.length - pos );
				if (( len < 0 )) 
				{
					len = 0;
				}
				
			}
			
		}
		
		T[] a = this.__a;
		T[] ret = ((T[]) new Object[len]);
		java.lang.System.arraycopy(a, pos, ret, 0, len);
		haxe.root.Array<T> ret1 = Array.ofNative(ret);
		int end = ( pos + len );
		java.lang.System.arraycopy(a, end, a, pos, ( this.length - end ));
		this.length -= len;
		while ((  -- len >= 0 ))
		{
			a[( this.length + len )] = null;
		}
		
		return ret1;
	}
	
	
	public void spliceVoid(int pos, int len)
	{
		if (( len < 0 )) 
		{
			return ;
		}
		
		if (( pos < 0 )) 
		{
			pos = ( this.length + pos );
			if (( pos < 0 )) 
			{
				pos = 0;
			}
			
		}
		
		if (( pos > this.length )) 
		{
			pos = 0;
			len = 0;
		}
		else
		{
			if (( ( pos + len ) > this.length )) 
			{
				len = ( this.length - pos );
				if (( len < 0 )) 
				{
					len = 0;
				}
				
			}
			
		}
		
		T[] a = this.__a;
		int end = ( pos + len );
		java.lang.System.arraycopy(a, end, a, pos, ( this.length - end ));
		this.length -= len;
		while ((  -- len >= 0 ))
		{
			a[( this.length + len )] = null;
		}
		
	}
	
	
	@Override public java.lang.String toString()
	{
		haxe.root.StringBuf ret = new haxe.root.StringBuf();
		T[] a = this.__a;
		ret.add(haxe.lang.Runtime.toString("["));
		boolean first = true;
		{
			int _g1 = 0;
			int _g = this.length;
			while (( _g1 < _g ))
			{
				int i = _g1++;
				if (first) 
				{
					first = false;
				}
				else
				{
					ret.add(haxe.lang.Runtime.toString(","));
				}
				
				ret.add(a[i]);
			}
			
		}
		
		ret.add(haxe.lang.Runtime.toString("]"));
		return ret.toString();
	}
	
	
	public void unshift(T x)
	{
		T[] __a = this.__a;
		int length = this.length;
		if (( length >= __a.length )) 
		{
			int newLen = ( (( length << 1 )) + 1 );
			T[] newarr = ((T[]) new Object[newLen]);
			java.lang.System.arraycopy(__a, 0, newarr, 1, length);
			this.__a = newarr;
		}
		else
		{
			java.lang.System.arraycopy(__a, 0, __a, 1, length);
		}
		
		this.__a[0] = x;
		 ++ this.length;
	}
	
	
	public void insert(int pos, T x)
	{
		int l = this.length;
		if (( pos < 0 )) 
		{
			pos = ( l + pos );
			if (( pos < 0 )) 
			{
				pos = 0;
			}
			
		}
		
		if (( pos >= l )) 
		{
			this.push(x);
			return ;
		}
		else
		{
			if (( pos == 0 )) 
			{
				this.unshift(x);
				return ;
			}
			
		}
		
		if (( l >= this.__a.length )) 
		{
			int newLen = ( (( this.length << 1 )) + 1 );
			T[] newarr = ((T[]) new Object[newLen]);
			java.lang.System.arraycopy(this.__a, 0, newarr, 0, pos);
			newarr[pos] = x;
			java.lang.System.arraycopy(this.__a, pos, newarr, ( pos + 1 ), ( l - pos ));
			this.__a = newarr;
			 ++ this.length;
		}
		else
		{
			T[] __a = this.__a;
			java.lang.System.arraycopy(__a, pos, __a, ( pos + 1 ), ( l - pos ));
			java.lang.System.arraycopy(__a, 0, __a, 0, pos);
			__a[pos] = x;
			 ++ this.length;
		}
		
	}
	
	
	public boolean remove(T x)
	{
		T[] __a = this.__a;
		int i = -1;
		int length = this.length;
		while ((  ++ i < length ))
		{
			if (haxe.lang.Runtime.eq(__a[i], x)) 
			{
				java.lang.System.arraycopy(__a, ( i + 1 ), __a, i, ( ( length - i ) - 1 ));
				__a[ -- this.length] = null;
				return true;
			}
			
		}
		
		return false;
	}
	
	
	public int indexOf(T x, java.lang.Object fromIndex)
	{
		int len = this.length;
		T[] a = this.__a;
		int i = ( (haxe.lang.Runtime.eq(fromIndex, null)) ? (0) : haxe.lang.Runtime.toInt(fromIndex));
		if (( i < 0 )) 
		{
			i += len;
			if (( i < 0 )) 
			{
				i = 0;
			}
			
		}
		
		while (( i < len ))
		{
			if (haxe.lang.Runtime.eq(a[i], x)) 
			{
				return i;
			}
			
			 ++ i;
		}
		
		return -1;
	}
	
	
	public int lastIndexOf(T x, java.lang.Object fromIndex)
	{
		int len = this.length;
		T[] a = this.__a;
		int i = ( (haxe.lang.Runtime.eq(fromIndex, null)) ? (( len - 1 )) : haxe.lang.Runtime.toInt(fromIndex));
		if (( i >= len )) 
		{
			i = ( len - 1 );
		}
		else
		{
			if (( i < 0 )) 
			{
				i += len;
			}
			
		}
		
		while (( i >= 0 ))
		{
			if (haxe.lang.Runtime.eq(a[i], x)) 
			{
				return i;
			}
			
			 -- i;
		}
		
		return -1;
	}
	
	
	public haxe.root.Array<T> copy()
	{
		int len = this.length;
		T[] __a = this.__a;
		T[] newarr = ((T[]) new Object[len]);
		java.lang.System.arraycopy(__a, 0, newarr, 0, len);
		return Array.ofNative(newarr);
	}
	
	
	public java.lang.Object iterator()
	{
		return new ArrayIterator<T>(this);
	}
	
	
	public <S> haxe.root.Array<S> map(haxe.lang.Function f)
	{
		haxe.root.Array<S> ret = new haxe.root.Array<S>(( (S[]) (new java.lang.Object[] {}) ));
		{
			int _g = 0;
			haxe.root.Array<T> _g1 = this;
			while (( _g < _g1.length ))
			{
				T elt = _g1.__get(_g);
				 ++ _g;
				ret.push(((S) (f.__hx_invoke1_o(0.0, elt)) ));
			}
			
		}
		
		return ret;
	}
	
	
	public haxe.root.Array<T> filter(haxe.lang.Function f)
	{
		haxe.root.Array<T> ret = new haxe.root.Array<T>(( (T[]) (new java.lang.Object[] {}) ));
		{
			int _g = 0;
			haxe.root.Array<T> _g1 = this;
			while (( _g < _g1.length ))
			{
				T elt = _g1.__get(_g);
				 ++ _g;
				if (haxe.lang.Runtime.toBool(f.__hx_invoke1_o(0.0, elt))) 
				{
					ret.push(elt);
				}
				
			}
			
		}
		
		return ret;
	}
	
	
	public T __get(int idx)
	{
		T[] __a = this.__a;
		if (( ( idx >= __a.length ) || ( idx < 0 ) )) 
		{
			return null;
		}
		
		return __a[idx];
	}
	
	
	public T __set(int idx, T v)
	{
		T[] __a = this.__a;
		if (( idx >= __a.length )) 
		{
			int newl = ( idx + 1 );
			if (( idx == __a.length )) 
			{
				newl = ( (( idx << 1 )) + 1 );
			}
			
			T[] newArr = ((T[]) new Object[newl]);
			if (( this.length > 0 )) 
			{
				java.lang.System.arraycopy(__a, 0, newArr, 0, this.length);
			}
			
			__a = newArr;
			this.__a = __a;
		}
		
		if (( idx >= this.length )) 
		{
			this.length = ( idx + 1 );
		}
		
		return __a[idx] = v;
	}
	
	
	public T __unsafe_get(int idx)
	{
		return this.__a[idx];
	}
	
	
	public T __unsafe_set(int idx, T val)
	{
		return this.__a[idx] = val;
	}
	
	
	@Override public double __hx_setField_f(java.lang.String field, double value, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case -1106363674:
				{
					if (field.equals("length")) 
					{
						this.length = ((int) (value) );
						return value;
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_setField_f(field, value, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case 94337:
				{
					if (field.equals("__a")) 
					{
						this.__a = ((T[]) (value) );
						return value;
					}
					
					break;
				}
				
				
				case -1106363674:
				{
					if (field.equals("length")) 
					{
						this.length = haxe.lang.Runtime.toInt(value);
						return value;
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case -537840087:
				{
					if (field.equals("__unsafe_set")) 
					{
						return new haxe.lang.Closure(this, "__unsafe_set");
					}
					
					break;
				}
				
				
				case -1106363674:
				{
					if (field.equals("length")) 
					{
						return this.length;
					}
					
					break;
				}
				
				
				case -537851619:
				{
					if (field.equals("__unsafe_get")) 
					{
						return new haxe.lang.Closure(this, "__unsafe_get");
					}
					
					break;
				}
				
				
				case 94337:
				{
					if (field.equals("__a")) 
					{
						return this.__a;
					}
					
					break;
				}
				
				
				case 90678402:
				{
					if (field.equals("__set")) 
					{
						return new haxe.lang.Closure(this, "__set");
					}
					
					break;
				}
				
				
				case -1354795244:
				{
					if (field.equals("concat")) 
					{
						return new haxe.lang.Closure(this, "concat");
					}
					
					break;
				}
				
				
				case 90666870:
				{
					if (field.equals("__get")) 
					{
						return new haxe.lang.Closure(this, "__get");
					}
					
					break;
				}
				
				
				case -1238494133:
				{
					if (field.equals("concatNative")) 
					{
						return new haxe.lang.Closure(this, "concatNative");
					}
					
					break;
				}
				
				
				case -1274492040:
				{
					if (field.equals("filter")) 
					{
						return new haxe.lang.Closure(this, "filter");
					}
					
					break;
				}
				
				
				case 3267882:
				{
					if (field.equals("join")) 
					{
						return new haxe.lang.Closure(this, "join");
					}
					
					break;
				}
				
				
				case 107868:
				{
					if (field.equals("map")) 
					{
						return new haxe.lang.Closure(this, "map");
					}
					
					break;
				}
				
				
				case 111185:
				{
					if (field.equals("pop")) 
					{
						return new haxe.lang.Closure(this, "pop");
					}
					
					break;
				}
				
				
				case 1182533742:
				{
					if (field.equals("iterator")) 
					{
						return new haxe.lang.Closure(this, "iterator");
					}
					
					break;
				}
				
				
				case 3452698:
				{
					if (field.equals("push")) 
					{
						return new haxe.lang.Closure(this, "push");
					}
					
					break;
				}
				
				
				case 3059573:
				{
					if (field.equals("copy")) 
					{
						return new haxe.lang.Closure(this, "copy");
					}
					
					break;
				}
				
				
				case 1099846370:
				{
					if (field.equals("reverse")) 
					{
						return new haxe.lang.Closure(this, "reverse");
					}
					
					break;
				}
				
				
				case -467511597:
				{
					if (field.equals("lastIndexOf")) 
					{
						return new haxe.lang.Closure(this, "lastIndexOf");
					}
					
					break;
				}
				
				
				case 109407362:
				{
					if (field.equals("shift")) 
					{
						return new haxe.lang.Closure(this, "shift");
					}
					
					break;
				}
				
				
				case 1943291465:
				{
					if (field.equals("indexOf")) 
					{
						return new haxe.lang.Closure(this, "indexOf");
					}
					
					break;
				}
				
				
				case 109526418:
				{
					if (field.equals("slice")) 
					{
						return new haxe.lang.Closure(this, "slice");
					}
					
					break;
				}
				
				
				case -934610812:
				{
					if (field.equals("remove")) 
					{
						return new haxe.lang.Closure(this, "remove");
					}
					
					break;
				}
				
				
				case 3536286:
				{
					if (field.equals("sort")) 
					{
						return new haxe.lang.Closure(this, "sort");
					}
					
					break;
				}
				
				
				case -1183792455:
				{
					if (field.equals("insert")) 
					{
						return new haxe.lang.Closure(this, "insert");
					}
					
					break;
				}
				
				
				case 1301699851:
				{
					if (field.equals("quicksort")) 
					{
						return new haxe.lang.Closure(this, "quicksort");
					}
					
					break;
				}
				
				
				case -277637751:
				{
					if (field.equals("unshift")) 
					{
						return new haxe.lang.Closure(this, "unshift");
					}
					
					break;
				}
				
				
				case -895859076:
				{
					if (field.equals("splice")) 
					{
						return new haxe.lang.Closure(this, "splice");
					}
					
					break;
				}
				
				
				case -1776922004:
				{
					if (field.equals("toString")) 
					{
						return new haxe.lang.Closure(this, "toString");
					}
					
					break;
				}
				
				
				case -821858768:
				{
					if (field.equals("spliceVoid")) 
					{
						return new haxe.lang.Closure(this, "spliceVoid");
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public double __hx_getField_f(java.lang.String field, boolean throwErrors, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case -1106363674:
				{
					if (field.equals("length")) 
					{
						return this.length;
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_getField_f(field, throwErrors, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, haxe.root.Array dynargs)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case -537840087:
				{
					if (field.equals("__unsafe_set")) 
					{
						return this.__unsafe_set(haxe.lang.Runtime.toInt(dynargs.__get(0)), ((T) (dynargs.__get(1)) ));
					}
					
					break;
				}
				
				
				case -1354795244:
				{
					if (field.equals("concat")) 
					{
						return this.concat(((haxe.root.Array<T>) (dynargs.__get(0)) ));
					}
					
					break;
				}
				
				
				case -537851619:
				{
					if (field.equals("__unsafe_get")) 
					{
						return this.__unsafe_get(haxe.lang.Runtime.toInt(dynargs.__get(0)));
					}
					
					break;
				}
				
				
				case -1238494133:
				{
					if (field.equals("concatNative")) 
					{
						__temp_executeDef1 = false;
						this.concatNative(((T[]) (dynargs.__get(0)) ));
					}
					
					break;
				}
				
				
				case 90678402:
				{
					if (field.equals("__set")) 
					{
						return this.__set(haxe.lang.Runtime.toInt(dynargs.__get(0)), ((T) (dynargs.__get(1)) ));
					}
					
					break;
				}
				
				
				case 3267882:
				{
					if (field.equals("join")) 
					{
						return this.join(haxe.lang.Runtime.toString(dynargs.__get(0)));
					}
					
					break;
				}
				
				
				case 90666870:
				{
					if (field.equals("__get")) 
					{
						return this.__get(haxe.lang.Runtime.toInt(dynargs.__get(0)));
					}
					
					break;
				}
				
				
				case 111185:
				{
					if (field.equals("pop")) 
					{
						return this.pop();
					}
					
					break;
				}
				
				
				case -1274492040:
				{
					if (field.equals("filter")) 
					{
						return this.filter(((haxe.lang.Function) (dynargs.__get(0)) ));
					}
					
					break;
				}
				
				
				case 3452698:
				{
					if (field.equals("push")) 
					{
						return this.push(((T) (dynargs.__get(0)) ));
					}
					
					break;
				}
				
				
				case 107868:
				{
					if (field.equals("map")) 
					{
						return this.map(((haxe.lang.Function) (dynargs.__get(0)) ));
					}
					
					break;
				}
				
				
				case 1099846370:
				{
					if (field.equals("reverse")) 
					{
						__temp_executeDef1 = false;
						this.reverse();
					}
					
					break;
				}
				
				
				case 1182533742:
				{
					if (field.equals("iterator")) 
					{
						return this.iterator();
					}
					
					break;
				}
				
				
				case 109407362:
				{
					if (field.equals("shift")) 
					{
						return this.shift();
					}
					
					break;
				}
				
				
				case 3059573:
				{
					if (field.equals("copy")) 
					{
						return this.copy();
					}
					
					break;
				}
				
				
				case 109526418:
				{
					if (field.equals("slice")) 
					{
						return this.slice(haxe.lang.Runtime.toInt(dynargs.__get(0)), dynargs.__get(1));
					}
					
					break;
				}
				
				
				case -467511597:
				{
					if (field.equals("lastIndexOf")) 
					{
						return this.lastIndexOf(((T) (dynargs.__get(0)) ), dynargs.__get(1));
					}
					
					break;
				}
				
				
				case 3536286:
				{
					if (field.equals("sort")) 
					{
						__temp_executeDef1 = false;
						this.sort(((haxe.lang.Function) (dynargs.__get(0)) ));
					}
					
					break;
				}
				
				
				case 1943291465:
				{
					if (field.equals("indexOf")) 
					{
						return this.indexOf(((T) (dynargs.__get(0)) ), dynargs.__get(1));
					}
					
					break;
				}
				
				
				case 1301699851:
				{
					if (field.equals("quicksort")) 
					{
						__temp_executeDef1 = false;
						this.quicksort(haxe.lang.Runtime.toInt(dynargs.__get(0)), haxe.lang.Runtime.toInt(dynargs.__get(1)), ((haxe.lang.Function) (dynargs.__get(2)) ));
					}
					
					break;
				}
				
				
				case -934610812:
				{
					if (field.equals("remove")) 
					{
						return this.remove(((T) (dynargs.__get(0)) ));
					}
					
					break;
				}
				
				
				case -895859076:
				{
					if (field.equals("splice")) 
					{
						return this.splice(haxe.lang.Runtime.toInt(dynargs.__get(0)), haxe.lang.Runtime.toInt(dynargs.__get(1)));
					}
					
					break;
				}
				
				
				case -1183792455:
				{
					if (field.equals("insert")) 
					{
						__temp_executeDef1 = false;
						this.insert(haxe.lang.Runtime.toInt(dynargs.__get(0)), ((T) (dynargs.__get(1)) ));
					}
					
					break;
				}
				
				
				case -821858768:
				{
					if (field.equals("spliceVoid")) 
					{
						__temp_executeDef1 = false;
						this.spliceVoid(haxe.lang.Runtime.toInt(dynargs.__get(0)), haxe.lang.Runtime.toInt(dynargs.__get(1)));
					}
					
					break;
				}
				
				
				case -277637751:
				{
					if (field.equals("unshift")) 
					{
						__temp_executeDef1 = false;
						this.unshift(((T) (dynargs.__get(0)) ));
					}
					
					break;
				}
				
				
				case -1776922004:
				{
					if (field.equals("toString")) 
					{
						return this.toString();
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_invokeField(field, dynargs);
			}
			
		}
		
		return null;
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		baseArr.push("__a");
		baseArr.push("length");
		super.__hx_getFields(baseArr);
	}


	@SuppressWarnings(value={"rawtypes", "unchecked"})
	public static final class ArrayIterator<T> extends haxe.lang.HxObject
	{
		public ArrayIterator(haxe.lang.EmptyObject empty)
		{
		}


		public ArrayIterator(Array<T> a)
		{
			ArrayIterator.__hx_ctor__Array_ArrayIterator(this, a);
		}


		public static <T_c> void __hx_ctor__Array_ArrayIterator(ArrayIterator<T_c> __hx_this, Array<T_c> a)
		{
			__hx_this.arr = a;
			__hx_this.len = a.length;
			__hx_this.i = 0;
		}


		public Array<T> arr;

		public int len;

		public int i;

		public boolean hasNext()
		{
			return ( this.i < this.len );
		}


		public T next()
		{
			return this.arr.__get(this.i++);
		}


		@Override public double __hx_setField_f(String field, double value, boolean handleProperties)
		{
			{
				boolean __temp_executeDef1 = true;
				switch (field.hashCode())
				{
					case 105:
					{
						if (field.equals("i"))
						{
							this.i = ((int) (value) );
							return value;
						}

						break;
					}


					case 107029:
					{
						if (field.equals("len"))
						{
							this.len = ((int) (value) );
							return value;
						}

						break;
					}


				}

				if (__temp_executeDef1)
				{
					return super.__hx_setField_f(field, value, handleProperties);
				}
				else
				{
					throw null;
				}

			}

		}


		@Override public Object __hx_setField(String field, Object value, boolean handleProperties)
		{
			{
				boolean __temp_executeDef1 = true;
				switch (field.hashCode())
				{
					case 105:
					{
						if (field.equals("i"))
						{
							this.i = haxe.lang.Runtime.toInt(value);
							return value;
						}

						break;
					}


					case 96865:
					{
						if (field.equals("arr"))
						{
							this.arr = ((Array<T>) (value) );
							return value;
						}

						break;
					}


					case 107029:
					{
						if (field.equals("len"))
						{
							this.len = haxe.lang.Runtime.toInt(value);
							return value;
						}

						break;
					}


				}

				if (__temp_executeDef1)
				{
					return super.__hx_setField(field, value, handleProperties);
				}
				else
				{
					throw null;
				}

			}

		}


		@Override public Object __hx_getField(String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
		{
			{
				boolean __temp_executeDef1 = true;
				switch (field.hashCode())
				{
					case 3377907:
					{
						if (field.equals("next"))
						{
							return new haxe.lang.Closure(this, "next");
						}

						break;
					}


					case 96865:
					{
						if (field.equals("arr"))
						{
							return this.arr;
						}

						break;
					}


					case 696759469:
					{
						if (field.equals("hasNext"))
						{
							return new haxe.lang.Closure(this, "hasNext");
						}

						break;
					}


					case 107029:
					{
						if (field.equals("len"))
						{
							return this.len;
						}

						break;
					}


					case 105:
					{
						if (field.equals("i"))
						{
							return this.i;
						}

						break;
					}


				}

				if (__temp_executeDef1)
				{
					return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
				}
				else
				{
					throw null;
				}

			}

		}


		@Override public double __hx_getField_f(String field, boolean throwErrors, boolean handleProperties)
		{
			{
				boolean __temp_executeDef1 = true;
				switch (field.hashCode())
				{
					case 105:
					{
						if (field.equals("i"))
						{
							return this.i;
						}

						break;
					}


					case 107029:
					{
						if (field.equals("len"))
						{
							return this.len;
						}

						break;
					}


				}

				if (__temp_executeDef1)
				{
					return super.__hx_getField_f(field, throwErrors, handleProperties);
				}
				else
				{
					throw null;
				}

			}

		}


		@Override public Object __hx_invokeField(String field, Array dynargs)
		{
			{
				boolean __temp_executeDef1 = true;
				switch (field.hashCode())
				{
					case 3377907:
					{
						if (field.equals("next"))
						{
							return this.next();
						}

						break;
					}


					case 696759469:
					{
						if (field.equals("hasNext"))
						{
							return this.hasNext();
						}

						break;
					}


				}

				if (__temp_executeDef1)
				{
					return super.__hx_invokeField(field, dynargs);
				}
				else
				{
					throw null;
				}

			}

		}


		@Override public void __hx_getFields(Array<String> baseArr)
		{
			baseArr.push("i");
			baseArr.push("len");
			baseArr.push("arr");
			super.__hx_getFields(baseArr);
		}


	}
}


