// Generated by Haxe 3.4.2
package hxDaedalus.iterators;

@SuppressWarnings(value={"rawtypes"})
public class FromVertexToOutgoingEdges extends haxe.lang.HxObject
{
	public FromVertexToOutgoingEdges(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public FromVertexToOutgoingEdges()
	{
		hxDaedalus.iterators.FromVertexToOutgoingEdges.__hx_ctor_hxDaedalus_iterators_FromVertexToOutgoingEdges(this);
	}
	
	
	public static void __hx_ctor_hxDaedalus_iterators_FromVertexToOutgoingEdges(hxDaedalus.iterators.FromVertexToOutgoingEdges __hx_this)
	{
		__hx_this.realEdgesOnly = true;
	}
	
	
	
	
	public hxDaedalus.data.Vertex _fromVertex;
	
	public hxDaedalus.data.Edge _nextEdge;
	
	public boolean realEdgesOnly;
	
	public hxDaedalus.data.Vertex set_fromVertex(hxDaedalus.data.Vertex value)
	{
		this._fromVertex = value;
		this._nextEdge = this._fromVertex.get_edge();
		while (( this.realEdgesOnly &&  ! (this._nextEdge.get_isReal())  ))
		{
			this._nextEdge = this._nextEdge.get_rotLeftEdge();
		}
		
		return value;
	}
	
	
	public hxDaedalus.data.Edge _resultEdge;
	
	public hxDaedalus.data.Edge next()
	{
		if (( this._nextEdge != null )) 
		{
			this._resultEdge = this._nextEdge;
			while (true)
			{
				this._nextEdge = this._nextEdge.get_rotLeftEdge();
				if (( this._nextEdge == this._fromVertex.get_edge() )) 
				{
					this._nextEdge = null;
					break;
				}
				
				if ( ! ((( this.realEdgesOnly &&  ! (this._nextEdge.get_isReal())  ))) ) 
				{
					break;
				}
				
			}
			
		}
		else
		{
			this._resultEdge = null;
		}
		
		return this._resultEdge;
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case 516008217:
				{
					if (field.equals("_resultEdge")) 
					{
						this._resultEdge = ((hxDaedalus.data.Edge) (value) );
						return value;
					}
					
					break;
				}
				
				
				case -2064921106:
				{
					if (field.equals("fromVertex")) 
					{
						this.set_fromVertex(((hxDaedalus.data.Vertex) (value) ));
						return value;
					}
					
					break;
				}
				
				
				case 1055882020:
				{
					if (field.equals("realEdgesOnly")) 
					{
						this.realEdgesOnly = haxe.lang.Runtime.toBool(value);
						return value;
					}
					
					break;
				}
				
				
				case -976608371:
				{
					if (field.equals("_fromVertex")) 
					{
						this._fromVertex = ((hxDaedalus.data.Vertex) (value) );
						return value;
					}
					
					break;
				}
				
				
				case 1514466479:
				{
					if (field.equals("_nextEdge")) 
					{
						this._nextEdge = ((hxDaedalus.data.Edge) (value) );
						return value;
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case 3377907:
				{
					if (field.equals("next")) 
					{
						return new haxe.lang.Closure(this, "next");
					}
					
					break;
				}
				
				
				case -976608371:
				{
					if (field.equals("_fromVertex")) 
					{
						return this._fromVertex;
					}
					
					break;
				}
				
				
				case 516008217:
				{
					if (field.equals("_resultEdge")) 
					{
						return this._resultEdge;
					}
					
					break;
				}
				
				
				case 1514466479:
				{
					if (field.equals("_nextEdge")) 
					{
						return this._nextEdge;
					}
					
					break;
				}
				
				
				case -761514517:
				{
					if (field.equals("set_fromVertex")) 
					{
						return new haxe.lang.Closure(this, "set_fromVertex");
					}
					
					break;
				}
				
				
				case 1055882020:
				{
					if (field.equals("realEdgesOnly")) 
					{
						return this.realEdgesOnly;
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, haxe.root.Array dynargs)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case 3377907:
				{
					if (field.equals("next")) 
					{
						return this.next();
					}
					
					break;
				}
				
				
				case -761514517:
				{
					if (field.equals("set_fromVertex")) 
					{
						return this.set_fromVertex(((hxDaedalus.data.Vertex) (dynargs.__get(0)) ));
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_invokeField(field, dynargs);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		baseArr.push("_resultEdge");
		baseArr.push("realEdgesOnly");
		baseArr.push("_nextEdge");
		baseArr.push("_fromVertex");
		baseArr.push("fromVertex");
		super.__hx_getFields(baseArr);
	}
	
	
}


