// Generated by Haxe 3.4.2
package haxe.io;

@SuppressWarnings(value={"rawtypes"})
public class Eof extends haxe.lang.HxObject
{
	public Eof(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Eof()
	{
		haxe.io.Eof.__hx_ctor_haxe_io_Eof(this);
	}
	
	
	public static void __hx_ctor_haxe_io_Eof(haxe.io.Eof __hx_this)
	{
	}
	
	
	@Override public java.lang.String toString()
	{
		return "Eof";
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case -1776922004:
				{
					if (field.equals("toString")) 
					{
						return new haxe.lang.Closure(this, "toString");
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, haxe.root.Array dynargs)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case -1776922004:
				{
					if (field.equals("toString")) 
					{
						return this.toString();
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_invokeField(field, dynargs);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
}


