// Generated by Haxe 3.4.2
package hxDaedalus.data;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class ConstraintShape extends haxe.lang.HxObject
{
	static
	{
		hxDaedalus.data.ConstraintShape.INC = 0;
	}
	
	public ConstraintShape(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public ConstraintShape()
	{
		hxDaedalus.data.ConstraintShape.__hx_ctor_hxDaedalus_data_ConstraintShape(this);
	}
	
	
	public static void __hx_ctor_hxDaedalus_data_ConstraintShape(hxDaedalus.data.ConstraintShape __hx_this)
	{
		__hx_this._id = hxDaedalus.data.ConstraintShape.INC;
		hxDaedalus.data.ConstraintShape.INC++;
		__hx_this.segments = new haxe.root.Array<hxDaedalus.data.ConstraintSegment>();
	}
	
	
	public static int INC;
	
	
	
	public haxe.root.Array<hxDaedalus.data.ConstraintSegment> segments;
	
	public int _id;
	
	public int get_id()
	{
		return this._id;
	}
	
	
	public void dispose()
	{
		while (( this.segments.length > 0 ))
		{
			((hxDaedalus.data.ConstraintSegment) (this.segments.pop()) ).dispose();
		}
		
		this.segments = null;
	}
	
	
	@Override public double __hx_setField_f(java.lang.String field, double value, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case 94650:
				{
					if (field.equals("_id")) 
					{
						this._id = ((int) (value) );
						return value;
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_setField_f(field, value, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case 94650:
				{
					if (field.equals("_id")) 
					{
						this._id = haxe.lang.Runtime.toInt(value);
						return value;
					}
					
					break;
				}
				
				
				case 1055868832:
				{
					if (field.equals("segments")) 
					{
						this.segments = ((haxe.root.Array<hxDaedalus.data.ConstraintSegment>) (value) );
						return value;
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case 1671767583:
				{
					if (field.equals("dispose")) 
					{
						return new haxe.lang.Closure(this, "dispose");
					}
					
					break;
				}
				
				
				case 3355:
				{
					if (field.equals("id")) 
					{
						return this.get_id();
					}
					
					break;
				}
				
				
				case -1249338716:
				{
					if (field.equals("get_id")) 
					{
						return new haxe.lang.Closure(this, "get_id");
					}
					
					break;
				}
				
				
				case 1055868832:
				{
					if (field.equals("segments")) 
					{
						return this.segments;
					}
					
					break;
				}
				
				
				case 94650:
				{
					if (field.equals("_id")) 
					{
						return this._id;
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public double __hx_getField_f(java.lang.String field, boolean throwErrors, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case 94650:
				{
					if (field.equals("_id")) 
					{
						return this._id;
					}
					
					break;
				}
				
				
				case 3355:
				{
					if (field.equals("id")) 
					{
						return this.get_id();
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_getField_f(field, throwErrors, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, haxe.root.Array dynargs)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case 1671767583:
				{
					if (field.equals("dispose")) 
					{
						__temp_executeDef1 = false;
						this.dispose();
					}
					
					break;
				}
				
				
				case -1249338716:
				{
					if (field.equals("get_id")) 
					{
						return this.get_id();
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_invokeField(field, dynargs);
			}
			
		}
		
		return null;
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		baseArr.push("_id");
		baseArr.push("segments");
		baseArr.push("id");
		super.__hx_getFields(baseArr);
	}
	
	
}


