// Generated by Haxe 3.4.2
package hxDaedalus.data;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Edge extends haxe.lang.HxObject
{
	static
	{
		hxDaedalus.data.Edge.INC = 0;
	}
	
	public Edge(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Edge()
	{
		hxDaedalus.data.Edge.__hx_ctor_hxDaedalus_data_Edge(this);
	}
	
	
	public static void __hx_ctor_hxDaedalus_data_Edge(hxDaedalus.data.Edge __hx_this)
	{
		__hx_this.colorDebug = -1;
		__hx_this._id = hxDaedalus.data.Edge.INC;
		hxDaedalus.data.Edge.INC++;
		__hx_this.fromConstraintSegments = new haxe.root.Array<hxDaedalus.data.ConstraintSegment>();
	}
	
	
	public static int INC;
	
	
	
	
	
	
	
	
	
	
	
	
	
	public haxe.root.Array<hxDaedalus.data.ConstraintSegment> fromConstraintSegments;
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	public int _id;
	
	public boolean _isReal;
	
	public boolean _isConstrained;
	
	public hxDaedalus.data.Vertex _originVertex;
	
	public hxDaedalus.data.Edge _oppositeEdge;
	
	public hxDaedalus.data.Edge _nextLeftEdge;
	
	public hxDaedalus.data.Face _leftFace;
	
	public int colorDebug;
	
	public int get_id()
	{
		return this._id;
	}
	
	
	public boolean get_isReal()
	{
		return this._isReal;
	}
	
	
	public boolean get_isConstrained()
	{
		return this._isConstrained;
	}
	
	
	public void setDatas(hxDaedalus.data.Vertex originVertex, hxDaedalus.data.Edge oppositeEdge, hxDaedalus.data.Edge nextLeftEdge, hxDaedalus.data.Face leftFace, java.lang.Object isReal, java.lang.Object isConstrained)
	{
		boolean __temp_isConstrained4 = ( (haxe.lang.Runtime.eq(isConstrained, null)) ? (false) : (haxe.lang.Runtime.toBool(isConstrained)) );
		boolean __temp_isReal3 = ( (haxe.lang.Runtime.eq(isReal, null)) ? (true) : (haxe.lang.Runtime.toBool(isReal)) );
		this._isConstrained = __temp_isConstrained4;
		this._isReal = __temp_isReal3;
		this._originVertex = originVertex;
		this._oppositeEdge = oppositeEdge;
		this._nextLeftEdge = nextLeftEdge;
		this._leftFace = leftFace;
	}
	
	
	public void addFromConstraintSegment(hxDaedalus.data.ConstraintSegment segment)
	{
		if (( this.fromConstraintSegments.indexOf(segment, null) == -1 )) 
		{
			this.fromConstraintSegments.push(segment);
		}
		
	}
	
	
	public void removeFromConstraintSegment(hxDaedalus.data.ConstraintSegment segment)
	{
		int index = this.fromConstraintSegments.indexOf(segment, null);
		if (( index != -1 )) 
		{
			this.fromConstraintSegments.splice(index, 1);
		}
		
	}
	
	
	public hxDaedalus.data.Vertex set_originVertex(hxDaedalus.data.Vertex value)
	{
		this._originVertex = value;
		return value;
	}
	
	
	public hxDaedalus.data.Edge set_nextLeftEdge(hxDaedalus.data.Edge value)
	{
		this._nextLeftEdge = value;
		return value;
	}
	
	
	public hxDaedalus.data.Face set_leftFace(hxDaedalus.data.Face value)
	{
		this._leftFace = value;
		return value;
	}
	
	
	public boolean set_isConstrained(boolean value)
	{
		this._isConstrained = value;
		return value;
	}
	
	
	public void dispose()
	{
		this._originVertex = null;
		this._oppositeEdge = null;
		this._nextLeftEdge = null;
		this._leftFace = null;
		this.fromConstraintSegments = null;
	}
	
	
	public hxDaedalus.data.Vertex get_originVertex()
	{
		return this._originVertex;
	}
	
	
	public hxDaedalus.data.Vertex get_destinationVertex()
	{
		return this.get_oppositeEdge().get_originVertex();
	}
	
	
	public hxDaedalus.data.Edge get_oppositeEdge()
	{
		return this._oppositeEdge;
	}
	
	
	public hxDaedalus.data.Edge get_nextLeftEdge()
	{
		return this._nextLeftEdge;
	}
	
	
	public hxDaedalus.data.Edge get_prevLeftEdge()
	{
		return this._nextLeftEdge.get_nextLeftEdge();
	}
	
	
	public hxDaedalus.data.Edge get_nextRightEdge()
	{
		return this._oppositeEdge.get_nextLeftEdge().get_nextLeftEdge().get_oppositeEdge();
	}
	
	
	public hxDaedalus.data.Edge get_prevRightEdge()
	{
		return this._oppositeEdge.get_nextLeftEdge().get_oppositeEdge();
	}
	
	
	public hxDaedalus.data.Edge get_rotLeftEdge()
	{
		return this._nextLeftEdge.get_nextLeftEdge().get_oppositeEdge();
	}
	
	
	public hxDaedalus.data.Edge get_rotRightEdge()
	{
		return this._oppositeEdge.get_nextLeftEdge();
	}
	
	
	public hxDaedalus.data.Face get_leftFace()
	{
		return this._leftFace;
	}
	
	
	public hxDaedalus.data.Face get_rightFace()
	{
		return this._oppositeEdge.get_leftFace();
	}
	
	
	@Override public java.lang.String toString()
	{
		return ( ( ( "edge " + this.get_originVertex().get_id() ) + " - " ) + this.get_destinationVertex().get_id() );
	}
	
	
	@Override public double __hx_setField_f(java.lang.String field, double value, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case 1264295088:
				{
					if (field.equals("colorDebug")) 
					{
						this.colorDebug = ((int) (value) );
						return value;
					}
					
					break;
				}
				
				
				case 94650:
				{
					if (field.equals("_id")) 
					{
						this._id = ((int) (value) );
						return value;
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_setField_f(field, value, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case 1264295088:
				{
					if (field.equals("colorDebug")) 
					{
						this.colorDebug = haxe.lang.Runtime.toInt(value);
						return value;
					}
					
					break;
				}
				
				
				case 1278230732:
				{
					if (field.equals("isConstrained")) 
					{
						this.set_isConstrained(haxe.lang.Runtime.toBool(value));
						return value;
					}
					
					break;
				}
				
				
				case 1808515171:
				{
					if (field.equals("_leftFace")) 
					{
						this._leftFace = ((hxDaedalus.data.Face) (value) );
						return value;
					}
					
					break;
				}
				
				
				case 1817499754:
				{
					if (field.equals("originVertex")) 
					{
						this.set_originVertex(((hxDaedalus.data.Vertex) (value) ));
						return value;
					}
					
					break;
				}
				
				
				case -1428235178:
				{
					if (field.equals("_nextLeftEdge")) 
					{
						this._nextLeftEdge = ((hxDaedalus.data.Edge) (value) );
						return value;
					}
					
					break;
				}
				
				
				case 675246711:
				{
					if (field.equals("nextLeftEdge")) 
					{
						this.set_nextLeftEdge(((hxDaedalus.data.Edge) (value) ));
						return value;
					}
					
					break;
				}
				
				
				case 1320793891:
				{
					if (field.equals("_oppositeEdge")) 
					{
						this._oppositeEdge = ((hxDaedalus.data.Edge) (value) );
						return value;
					}
					
					break;
				}
				
				
				case 1717997316:
				{
					if (field.equals("leftFace")) 
					{
						this.set_leftFace(((hxDaedalus.data.Face) (value) ));
						return value;
					}
					
					break;
				}
				
				
				case -285982135:
				{
					if (field.equals("_originVertex")) 
					{
						this._originVertex = ((hxDaedalus.data.Vertex) (value) );
						return value;
					}
					
					break;
				}
				
				
				case -528444953:
				{
					if (field.equals("fromConstraintSegments")) 
					{
						this.fromConstraintSegments = ((haxe.root.Array<hxDaedalus.data.ConstraintSegment>) (value) );
						return value;
					}
					
					break;
				}
				
				
				case 494801613:
				{
					if (field.equals("_isConstrained")) 
					{
						this._isConstrained = haxe.lang.Runtime.toBool(value);
						return value;
					}
					
					break;
				}
				
				
				case 94650:
				{
					if (field.equals("_id")) 
					{
						this._id = haxe.lang.Runtime.toInt(value);
						return value;
					}
					
					break;
				}
				
				
				case 1528312583:
				{
					if (field.equals("_isReal")) 
					{
						this._isReal = haxe.lang.Runtime.toBool(value);
						return value;
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case -1776922004:
				{
					if (field.equals("toString")) 
					{
						return new haxe.lang.Closure(this, "toString");
					}
					
					break;
				}
				
				
				case 3355:
				{
					if (field.equals("id")) 
					{
						return this.get_id();
					}
					
					break;
				}
				
				
				case -1054706448:
				{
					if (field.equals("get_rightFace")) 
					{
						return new haxe.lang.Closure(this, "get_rightFace");
					}
					
					break;
				}
				
				
				case -1180158488:
				{
					if (field.equals("isReal")) 
					{
						return this.get_isReal();
					}
					
					break;
				}
				
				
				case -205057587:
				{
					if (field.equals("get_leftFace")) 
					{
						return new haxe.lang.Closure(this, "get_leftFace");
					}
					
					break;
				}
				
				
				case 1278230732:
				{
					if (field.equals("isConstrained")) 
					{
						return this.get_isConstrained();
					}
					
					break;
				}
				
				
				case -674188245:
				{
					if (field.equals("get_rotRightEdge")) 
					{
						return new haxe.lang.Closure(this, "get_rotRightEdge");
					}
					
					break;
				}
				
				
				case 1817499754:
				{
					if (field.equals("originVertex")) 
					{
						return this.get_originVertex();
					}
					
					break;
				}
				
				
				case 84285938:
				{
					if (field.equals("get_rotLeftEdge")) 
					{
						return new haxe.lang.Closure(this, "get_rotLeftEdge");
					}
					
					break;
				}
				
				
				case 675246711:
				{
					if (field.equals("nextLeftEdge")) 
					{
						return this.get_nextLeftEdge();
					}
					
					break;
				}
				
				
				case 872828893:
				{
					if (field.equals("get_prevRightEdge")) 
					{
						return new haxe.lang.Closure(this, "get_prevRightEdge");
					}
					
					break;
				}
				
				
				case 1717997316:
				{
					if (field.equals("leftFace")) 
					{
						return this.get_leftFace();
					}
					
					break;
				}
				
				
				case 392249117:
				{
					if (field.equals("get_nextRightEdge")) 
					{
						return new haxe.lang.Closure(this, "get_nextRightEdge");
					}
					
					break;
				}
				
				
				case -528444953:
				{
					if (field.equals("fromConstraintSegments")) 
					{
						return this.fromConstraintSegments;
					}
					
					break;
				}
				
				
				case -558546944:
				{
					if (field.equals("get_prevLeftEdge")) 
					{
						return new haxe.lang.Closure(this, "get_prevLeftEdge");
					}
					
					break;
				}
				
				
				case -1558175918:
				{
					if (field.equals("destinationVertex")) 
					{
						return this.get_destinationVertex();
					}
					
					break;
				}
				
				
				case 949971136:
				{
					if (field.equals("get_nextLeftEdge")) 
					{
						return new haxe.lang.Closure(this, "get_nextLeftEdge");
					}
					
					break;
				}
				
				
				case -870691516:
				{
					if (field.equals("oppositeEdge")) 
					{
						return this.get_oppositeEdge();
					}
					
					break;
				}
				
				
				case -595967091:
				{
					if (field.equals("get_oppositeEdge")) 
					{
						return new haxe.lang.Closure(this, "get_oppositeEdge");
					}
					
					break;
				}
				
				
				case -833271369:
				{
					if (field.equals("prevLeftEdge")) 
					{
						return this.get_prevLeftEdge();
					}
					
					break;
				}
				
				
				case 987475625:
				{
					if (field.equals("get_destinationVertex")) 
					{
						return new haxe.lang.Closure(this, "get_destinationVertex");
					}
					
					break;
				}
				
				
				case 465726534:
				{
					if (field.equals("nextRightEdge")) 
					{
						return this.get_nextRightEdge();
					}
					
					break;
				}
				
				
				case 2092224179:
				{
					if (field.equals("get_originVertex")) 
					{
						return new haxe.lang.Closure(this, "get_originVertex");
					}
					
					break;
				}
				
				
				case 946306310:
				{
					if (field.equals("prevRightEdge")) 
					{
						return this.get_prevRightEdge();
					}
					
					break;
				}
				
				
				case 1671767583:
				{
					if (field.equals("dispose")) 
					{
						return new haxe.lang.Closure(this, "dispose");
					}
					
					break;
				}
				
				
				case -755860133:
				{
					if (field.equals("rotLeftEdge")) 
					{
						return this.get_rotLeftEdge();
					}
					
					break;
				}
				
				
				case 264600495:
				{
					if (field.equals("set_isConstrained")) 
					{
						return new haxe.lang.Closure(this, "set_isConstrained");
					}
					
					break;
				}
				
				
				case -948912670:
				{
					if (field.equals("rotRightEdge")) 
					{
						return this.get_rotRightEdge();
					}
					
					break;
				}
				
				
				case 1343935041:
				{
					if (field.equals("set_leftFace")) 
					{
						return new haxe.lang.Closure(this, "set_leftFace");
					}
					
					break;
				}
				
				
				case -1569546599:
				{
					if (field.equals("rightFace")) 
					{
						return this.get_rightFace();
					}
					
					break;
				}
				
				
				case -881471692:
				{
					if (field.equals("set_nextLeftEdge")) 
					{
						return new haxe.lang.Closure(this, "set_nextLeftEdge");
					}
					
					break;
				}
				
				
				case 94650:
				{
					if (field.equals("_id")) 
					{
						return this._id;
					}
					
					break;
				}
				
				
				case 260781351:
				{
					if (field.equals("set_originVertex")) 
					{
						return new haxe.lang.Closure(this, "set_originVertex");
					}
					
					break;
				}
				
				
				case 1528312583:
				{
					if (field.equals("_isReal")) 
					{
						return this._isReal;
					}
					
					break;
				}
				
				
				case 1170407912:
				{
					if (field.equals("removeFromConstraintSegment")) 
					{
						return new haxe.lang.Closure(this, "removeFromConstraintSegment");
					}
					
					break;
				}
				
				
				case 494801613:
				{
					if (field.equals("_isConstrained")) 
					{
						return this._isConstrained;
					}
					
					break;
				}
				
				
				case 910337515:
				{
					if (field.equals("addFromConstraintSegment")) 
					{
						return new haxe.lang.Closure(this, "addFromConstraintSegment");
					}
					
					break;
				}
				
				
				case -285982135:
				{
					if (field.equals("_originVertex")) 
					{
						return this._originVertex;
					}
					
					break;
				}
				
				
				case 1390069447:
				{
					if (field.equals("setDatas")) 
					{
						return new haxe.lang.Closure(this, "setDatas");
					}
					
					break;
				}
				
				
				case 1320793891:
				{
					if (field.equals("_oppositeEdge")) 
					{
						return this._oppositeEdge;
					}
					
					break;
				}
				
				
				case 1204753315:
				{
					if (field.equals("get_isConstrained")) 
					{
						return new haxe.lang.Closure(this, "get_isConstrained");
					}
					
					break;
				}
				
				
				case -1428235178:
				{
					if (field.equals("_nextLeftEdge")) 
					{
						return this._nextLeftEdge;
					}
					
					break;
				}
				
				
				case 900519665:
				{
					if (field.equals("get_isReal")) 
					{
						return new haxe.lang.Closure(this, "get_isReal");
					}
					
					break;
				}
				
				
				case 1808515171:
				{
					if (field.equals("_leftFace")) 
					{
						return this._leftFace;
					}
					
					break;
				}
				
				
				case -1249338716:
				{
					if (field.equals("get_id")) 
					{
						return new haxe.lang.Closure(this, "get_id");
					}
					
					break;
				}
				
				
				case 1264295088:
				{
					if (field.equals("colorDebug")) 
					{
						return this.colorDebug;
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public double __hx_getField_f(java.lang.String field, boolean throwErrors, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case 1264295088:
				{
					if (field.equals("colorDebug")) 
					{
						return this.colorDebug;
					}
					
					break;
				}
				
				
				case 3355:
				{
					if (field.equals("id")) 
					{
						return this.get_id();
					}
					
					break;
				}
				
				
				case 94650:
				{
					if (field.equals("_id")) 
					{
						return this._id;
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_getField_f(field, throwErrors, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, haxe.root.Array dynargs)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case -1776922004:
				{
					if (field.equals("toString")) 
					{
						return this.toString();
					}
					
					break;
				}
				
				
				case -1249338716:
				{
					if (field.equals("get_id")) 
					{
						return this.get_id();
					}
					
					break;
				}
				
				
				case -1054706448:
				{
					if (field.equals("get_rightFace")) 
					{
						return this.get_rightFace();
					}
					
					break;
				}
				
				
				case 900519665:
				{
					if (field.equals("get_isReal")) 
					{
						return this.get_isReal();
					}
					
					break;
				}
				
				
				case -205057587:
				{
					if (field.equals("get_leftFace")) 
					{
						return this.get_leftFace();
					}
					
					break;
				}
				
				
				case 1204753315:
				{
					if (field.equals("get_isConstrained")) 
					{
						return this.get_isConstrained();
					}
					
					break;
				}
				
				
				case -674188245:
				{
					if (field.equals("get_rotRightEdge")) 
					{
						return this.get_rotRightEdge();
					}
					
					break;
				}
				
				
				case 1390069447:
				{
					if (field.equals("setDatas")) 
					{
						__temp_executeDef1 = false;
						this.setDatas(((hxDaedalus.data.Vertex) (dynargs.__get(0)) ), ((hxDaedalus.data.Edge) (dynargs.__get(1)) ), ((hxDaedalus.data.Edge) (dynargs.__get(2)) ), ((hxDaedalus.data.Face) (dynargs.__get(3)) ), dynargs.__get(4), dynargs.__get(5));
					}
					
					break;
				}
				
				
				case 84285938:
				{
					if (field.equals("get_rotLeftEdge")) 
					{
						return this.get_rotLeftEdge();
					}
					
					break;
				}
				
				
				case 910337515:
				{
					if (field.equals("addFromConstraintSegment")) 
					{
						__temp_executeDef1 = false;
						this.addFromConstraintSegment(((hxDaedalus.data.ConstraintSegment) (dynargs.__get(0)) ));
					}
					
					break;
				}
				
				
				case 872828893:
				{
					if (field.equals("get_prevRightEdge")) 
					{
						return this.get_prevRightEdge();
					}
					
					break;
				}
				
				
				case 1170407912:
				{
					if (field.equals("removeFromConstraintSegment")) 
					{
						__temp_executeDef1 = false;
						this.removeFromConstraintSegment(((hxDaedalus.data.ConstraintSegment) (dynargs.__get(0)) ));
					}
					
					break;
				}
				
				
				case 392249117:
				{
					if (field.equals("get_nextRightEdge")) 
					{
						return this.get_nextRightEdge();
					}
					
					break;
				}
				
				
				case 260781351:
				{
					if (field.equals("set_originVertex")) 
					{
						return this.set_originVertex(((hxDaedalus.data.Vertex) (dynargs.__get(0)) ));
					}
					
					break;
				}
				
				
				case -558546944:
				{
					if (field.equals("get_prevLeftEdge")) 
					{
						return this.get_prevLeftEdge();
					}
					
					break;
				}
				
				
				case -881471692:
				{
					if (field.equals("set_nextLeftEdge")) 
					{
						return this.set_nextLeftEdge(((hxDaedalus.data.Edge) (dynargs.__get(0)) ));
					}
					
					break;
				}
				
				
				case 949971136:
				{
					if (field.equals("get_nextLeftEdge")) 
					{
						return this.get_nextLeftEdge();
					}
					
					break;
				}
				
				
				case 1343935041:
				{
					if (field.equals("set_leftFace")) 
					{
						return this.set_leftFace(((hxDaedalus.data.Face) (dynargs.__get(0)) ));
					}
					
					break;
				}
				
				
				case -595967091:
				{
					if (field.equals("get_oppositeEdge")) 
					{
						return this.get_oppositeEdge();
					}
					
					break;
				}
				
				
				case 264600495:
				{
					if (field.equals("set_isConstrained")) 
					{
						return this.set_isConstrained(haxe.lang.Runtime.toBool(dynargs.__get(0)));
					}
					
					break;
				}
				
				
				case 987475625:
				{
					if (field.equals("get_destinationVertex")) 
					{
						return this.get_destinationVertex();
					}
					
					break;
				}
				
				
				case 1671767583:
				{
					if (field.equals("dispose")) 
					{
						__temp_executeDef1 = false;
						this.dispose();
					}
					
					break;
				}
				
				
				case 2092224179:
				{
					if (field.equals("get_originVertex")) 
					{
						return this.get_originVertex();
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_invokeField(field, dynargs);
			}
			
		}
		
		return null;
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		baseArr.push("colorDebug");
		baseArr.push("_leftFace");
		baseArr.push("_nextLeftEdge");
		baseArr.push("_oppositeEdge");
		baseArr.push("_originVertex");
		baseArr.push("_isConstrained");
		baseArr.push("_isReal");
		baseArr.push("_id");
		baseArr.push("rightFace");
		baseArr.push("rotRightEdge");
		baseArr.push("rotLeftEdge");
		baseArr.push("prevRightEdge");
		baseArr.push("nextRightEdge");
		baseArr.push("prevLeftEdge");
		baseArr.push("oppositeEdge");
		baseArr.push("destinationVertex");
		baseArr.push("fromConstraintSegments");
		baseArr.push("leftFace");
		baseArr.push("nextLeftEdge");
		baseArr.push("originVertex");
		baseArr.push("isConstrained");
		baseArr.push("isReal");
		baseArr.push("id");
		super.__hx_getFields(baseArr);
	}
	
	
}


