// Generated by Haxe 3.4.2
package hxDaedalus.data;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Vertex extends haxe.lang.HxObject
{
	static
	{
		hxDaedalus.data.Vertex.INC = 0;
	}
	
	public Vertex(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Vertex()
	{
		hxDaedalus.data.Vertex.__hx_ctor_hxDaedalus_data_Vertex(this);
	}
	
	
	public static void __hx_ctor_hxDaedalus_data_Vertex(hxDaedalus.data.Vertex __hx_this)
	{
		__hx_this.colorDebug = -1;
		__hx_this._id = hxDaedalus.data.Vertex.INC;
		hxDaedalus.data.Vertex.INC++;
		__hx_this._pos = new hxDaedalus.data.math.Point2D(null, null);
		__hx_this._fromConstraintSegments = new haxe.root.Array<hxDaedalus.data.ConstraintSegment>();
	}
	
	
	public static int INC;
	
	
	
	
	
	
	
	
	
	
	
	public int _id;
	
	public hxDaedalus.data.math.Point2D _pos;
	
	public boolean _isReal;
	
	public hxDaedalus.data.Edge _edge;
	
	public haxe.root.Array<hxDaedalus.data.ConstraintSegment> _fromConstraintSegments;
	
	public int colorDebug;
	
	public int get_id()
	{
		return this._id;
	}
	
	
	public boolean get_isReal()
	{
		return this._isReal;
	}
	
	
	public hxDaedalus.data.math.Point2D get_pos()
	{
		return this._pos;
	}
	
	
	public haxe.root.Array<hxDaedalus.data.ConstraintSegment> get_fromConstraintSegments()
	{
		return this._fromConstraintSegments;
	}
	
	
	public haxe.root.Array<hxDaedalus.data.ConstraintSegment> set_fromConstraintSegments(haxe.root.Array<hxDaedalus.data.ConstraintSegment> value)
	{
		return this._fromConstraintSegments = value;
	}
	
	
	public void setDatas(hxDaedalus.data.Edge edge, java.lang.Object isReal)
	{
		this._isReal = ( (haxe.lang.Runtime.eq(isReal, null)) ? (true) : (haxe.lang.Runtime.toBool(isReal)) );
		this._edge = edge;
	}
	
	
	public void addFromConstraintSegment(hxDaedalus.data.ConstraintSegment segment)
	{
		if (( this._fromConstraintSegments.indexOf(segment, null) == -1 )) 
		{
			this._fromConstraintSegments.push(segment);
		}
		
	}
	
	
	public void removeFromConstraintSegment(hxDaedalus.data.ConstraintSegment segment)
	{
		int index = this._fromConstraintSegments.indexOf(segment, null);
		if (( index != -1 )) 
		{
			this._fromConstraintSegments.splice(index, 1);
		}
		
	}
	
	
	public void dispose()
	{
		this._pos = null;
		this._edge = null;
		this._fromConstraintSegments = null;
	}
	
	
	public hxDaedalus.data.Edge get_edge()
	{
		return this._edge;
	}
	
	
	public hxDaedalus.data.Edge set_edge(hxDaedalus.data.Edge value)
	{
		return this._edge = value;
	}
	
	
	@Override public java.lang.String toString()
	{
		return ( "ver_id " + this._id );
	}
	
	
	@Override public double __hx_setField_f(java.lang.String field, double value, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case 1264295088:
				{
					if (field.equals("colorDebug")) 
					{
						this.colorDebug = ((int) (value) );
						return value;
					}
					
					break;
				}
				
				
				case 94650:
				{
					if (field.equals("_id")) 
					{
						this._id = ((int) (value) );
						return value;
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_setField_f(field, value, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case 1264295088:
				{
					if (field.equals("colorDebug")) 
					{
						this.colorDebug = haxe.lang.Runtime.toInt(value);
						return value;
					}
					
					break;
				}
				
				
				case -528444953:
				{
					if (field.equals("fromConstraintSegments")) 
					{
						this.set_fromConstraintSegments(((haxe.root.Array<hxDaedalus.data.ConstraintSegment>) (value) ));
						return value;
					}
					
					break;
				}
				
				
				case 1760063750:
				{
					if (field.equals("_fromConstraintSegments")) 
					{
						this._fromConstraintSegments = ((haxe.root.Array<hxDaedalus.data.ConstraintSegment>) (value) );
						return value;
					}
					
					break;
				}
				
				
				case 3108285:
				{
					if (field.equals("edge")) 
					{
						this.set_edge(((hxDaedalus.data.Edge) (value) ));
						return value;
					}
					
					break;
				}
				
				
				case 90842780:
				{
					if (field.equals("_edge")) 
					{
						this._edge = ((hxDaedalus.data.Edge) (value) );
						return value;
					}
					
					break;
				}
				
				
				case 94650:
				{
					if (field.equals("_id")) 
					{
						this._id = haxe.lang.Runtime.toInt(value);
						return value;
					}
					
					break;
				}
				
				
				case 1528312583:
				{
					if (field.equals("_isReal")) 
					{
						this._isReal = haxe.lang.Runtime.toBool(value);
						return value;
					}
					
					break;
				}
				
				
				case 2941333:
				{
					if (field.equals("_pos")) 
					{
						this._pos = ((hxDaedalus.data.math.Point2D) (value) );
						return value;
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case -1776922004:
				{
					if (field.equals("toString")) 
					{
						return new haxe.lang.Closure(this, "toString");
					}
					
					break;
				}
				
				
				case 3355:
				{
					if (field.equals("id")) 
					{
						return this.get_id();
					}
					
					break;
				}
				
				
				case 1415108474:
				{
					if (field.equals("set_edge")) 
					{
						return new haxe.lang.Closure(this, "set_edge");
					}
					
					break;
				}
				
				
				case -1180158488:
				{
					if (field.equals("isReal")) 
					{
						return this.get_isReal();
					}
					
					break;
				}
				
				
				case 1976220934:
				{
					if (field.equals("get_edge")) 
					{
						return new haxe.lang.Closure(this, "get_edge");
					}
					
					break;
				}
				
				
				case 111188:
				{
					if (field.equals("pos")) 
					{
						return this.get_pos();
					}
					
					break;
				}
				
				
				case 1671767583:
				{
					if (field.equals("dispose")) 
					{
						return new haxe.lang.Closure(this, "dispose");
					}
					
					break;
				}
				
				
				case -528444953:
				{
					if (field.equals("fromConstraintSegments")) 
					{
						return this.get_fromConstraintSegments();
					}
					
					break;
				}
				
				
				case 1170407912:
				{
					if (field.equals("removeFromConstraintSegment")) 
					{
						return new haxe.lang.Closure(this, "removeFromConstraintSegment");
					}
					
					break;
				}
				
				
				case 3108285:
				{
					if (field.equals("edge")) 
					{
						return this.get_edge();
					}
					
					break;
				}
				
				
				case 910337515:
				{
					if (field.equals("addFromConstraintSegment")) 
					{
						return new haxe.lang.Closure(this, "addFromConstraintSegment");
					}
					
					break;
				}
				
				
				case 94650:
				{
					if (field.equals("_id")) 
					{
						return this._id;
					}
					
					break;
				}
				
				
				case 1390069447:
				{
					if (field.equals("setDatas")) 
					{
						return new haxe.lang.Closure(this, "setDatas");
					}
					
					break;
				}
				
				
				case 2941333:
				{
					if (field.equals("_pos")) 
					{
						return this._pos;
					}
					
					break;
				}
				
				
				case -1790187932:
				{
					if (field.equals("set_fromConstraintSegments")) 
					{
						return new haxe.lang.Closure(this, "set_fromConstraintSegments");
					}
					
					break;
				}
				
				
				case 1528312583:
				{
					if (field.equals("_isReal")) 
					{
						return this._isReal;
					}
					
					break;
				}
				
				
				case 2132541680:
				{
					if (field.equals("get_fromConstraintSegments")) 
					{
						return new haxe.lang.Closure(this, "get_fromConstraintSegments");
					}
					
					break;
				}
				
				
				case 90842780:
				{
					if (field.equals("_edge")) 
					{
						return this._edge;
					}
					
					break;
				}
				
				
				case -74787349:
				{
					if (field.equals("get_pos")) 
					{
						return new haxe.lang.Closure(this, "get_pos");
					}
					
					break;
				}
				
				
				case 1760063750:
				{
					if (field.equals("_fromConstraintSegments")) 
					{
						return this._fromConstraintSegments;
					}
					
					break;
				}
				
				
				case 900519665:
				{
					if (field.equals("get_isReal")) 
					{
						return new haxe.lang.Closure(this, "get_isReal");
					}
					
					break;
				}
				
				
				case 1264295088:
				{
					if (field.equals("colorDebug")) 
					{
						return this.colorDebug;
					}
					
					break;
				}
				
				
				case -1249338716:
				{
					if (field.equals("get_id")) 
					{
						return new haxe.lang.Closure(this, "get_id");
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public double __hx_getField_f(java.lang.String field, boolean throwErrors, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case 1264295088:
				{
					if (field.equals("colorDebug")) 
					{
						return this.colorDebug;
					}
					
					break;
				}
				
				
				case 3355:
				{
					if (field.equals("id")) 
					{
						return this.get_id();
					}
					
					break;
				}
				
				
				case 94650:
				{
					if (field.equals("_id")) 
					{
						return this._id;
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_getField_f(field, throwErrors, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, haxe.root.Array dynargs)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case -1776922004:
				{
					if (field.equals("toString")) 
					{
						return this.toString();
					}
					
					break;
				}
				
				
				case -1249338716:
				{
					if (field.equals("get_id")) 
					{
						return this.get_id();
					}
					
					break;
				}
				
				
				case 1415108474:
				{
					if (field.equals("set_edge")) 
					{
						return this.set_edge(((hxDaedalus.data.Edge) (dynargs.__get(0)) ));
					}
					
					break;
				}
				
				
				case 900519665:
				{
					if (field.equals("get_isReal")) 
					{
						return this.get_isReal();
					}
					
					break;
				}
				
				
				case 1976220934:
				{
					if (field.equals("get_edge")) 
					{
						return this.get_edge();
					}
					
					break;
				}
				
				
				case -74787349:
				{
					if (field.equals("get_pos")) 
					{
						return this.get_pos();
					}
					
					break;
				}
				
				
				case 1671767583:
				{
					if (field.equals("dispose")) 
					{
						__temp_executeDef1 = false;
						this.dispose();
					}
					
					break;
				}
				
				
				case 2132541680:
				{
					if (field.equals("get_fromConstraintSegments")) 
					{
						return this.get_fromConstraintSegments();
					}
					
					break;
				}
				
				
				case 1170407912:
				{
					if (field.equals("removeFromConstraintSegment")) 
					{
						__temp_executeDef1 = false;
						this.removeFromConstraintSegment(((hxDaedalus.data.ConstraintSegment) (dynargs.__get(0)) ));
					}
					
					break;
				}
				
				
				case -1790187932:
				{
					if (field.equals("set_fromConstraintSegments")) 
					{
						return this.set_fromConstraintSegments(((haxe.root.Array<hxDaedalus.data.ConstraintSegment>) (dynargs.__get(0)) ));
					}
					
					break;
				}
				
				
				case 910337515:
				{
					if (field.equals("addFromConstraintSegment")) 
					{
						__temp_executeDef1 = false;
						this.addFromConstraintSegment(((hxDaedalus.data.ConstraintSegment) (dynargs.__get(0)) ));
					}
					
					break;
				}
				
				
				case 1390069447:
				{
					if (field.equals("setDatas")) 
					{
						__temp_executeDef1 = false;
						this.setDatas(((hxDaedalus.data.Edge) (dynargs.__get(0)) ), dynargs.__get(1));
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_invokeField(field, dynargs);
			}
			
		}
		
		return null;
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		baseArr.push("colorDebug");
		baseArr.push("_fromConstraintSegments");
		baseArr.push("_edge");
		baseArr.push("_isReal");
		baseArr.push("_pos");
		baseArr.push("_id");
		baseArr.push("edge");
		baseArr.push("fromConstraintSegments");
		baseArr.push("pos");
		baseArr.push("isReal");
		baseArr.push("id");
		super.__hx_getFields(baseArr);
	}
	
	
}


