// Generated by Haxe 3.4.2
package hxDaedalus.data.math;

public class EdgeData extends haxe.lang.HxObject
{
	public EdgeData(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public EdgeData()
	{
		hxDaedalus.data.math.EdgeData.__hx_ctor_hxDaedalus_data_math_EdgeData(this);
	}
	
	
	public static void __hx_ctor_hxDaedalus_data_math_EdgeData(hxDaedalus.data.math.EdgeData __hx_this)
	{
	}
	
	
	public double sumDistancesSquared;
	
	public double length;
	
	public int nodesCount;
	
	@Override public double __hx_setField_f(java.lang.String field, double value, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case 2082952414:
				{
					if (field.equals("nodesCount")) 
					{
						this.nodesCount = ((int) (value) );
						return value;
					}
					
					break;
				}
				
				
				case 1451318868:
				{
					if (field.equals("sumDistancesSquared")) 
					{
						this.sumDistancesSquared = value;
						return value;
					}
					
					break;
				}
				
				
				case -1106363674:
				{
					if (field.equals("length")) 
					{
						this.length = value;
						return value;
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_setField_f(field, value, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case 2082952414:
				{
					if (field.equals("nodesCount")) 
					{
						this.nodesCount = haxe.lang.Runtime.toInt(value);
						return value;
					}
					
					break;
				}
				
				
				case 1451318868:
				{
					if (field.equals("sumDistancesSquared")) 
					{
						this.sumDistancesSquared = haxe.lang.Runtime.toDouble(value);
						return value;
					}
					
					break;
				}
				
				
				case -1106363674:
				{
					if (field.equals("length")) 
					{
						this.length = haxe.lang.Runtime.toDouble(value);
						return value;
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case 2082952414:
				{
					if (field.equals("nodesCount")) 
					{
						return this.nodesCount;
					}
					
					break;
				}
				
				
				case 1451318868:
				{
					if (field.equals("sumDistancesSquared")) 
					{
						return this.sumDistancesSquared;
					}
					
					break;
				}
				
				
				case -1106363674:
				{
					if (field.equals("length")) 
					{
						return this.length;
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public double __hx_getField_f(java.lang.String field, boolean throwErrors, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case 2082952414:
				{
					if (field.equals("nodesCount")) 
					{
						return this.nodesCount;
					}
					
					break;
				}
				
				
				case 1451318868:
				{
					if (field.equals("sumDistancesSquared")) 
					{
						return this.sumDistancesSquared;
					}
					
					break;
				}
				
				
				case -1106363674:
				{
					if (field.equals("length")) 
					{
						return this.length;
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_getField_f(field, throwErrors, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		baseArr.push("nodesCount");
		baseArr.push("length");
		baseArr.push("sumDistancesSquared");
		super.__hx_getFields(baseArr);
	}
	
	
}


