// Generated by Haxe 3.4.2
package hxDaedalus.data.math;

public class Intersection extends haxe.lang.ParamEnum
{
	public Intersection(int index, java.lang.Object[] params)
	{
		super(index, params);
	}
	
	
	public static final java.lang.String[] __hx_constructs = new java.lang.String[]{"EVertex", "EEdge", "EFace", "ENull"};
	
	public static hxDaedalus.data.math.Intersection EVertex(hxDaedalus.data.Vertex vertex)
	{
		return new hxDaedalus.data.math.Intersection(0, new java.lang.Object[]{vertex});
	}
	
	
	public static hxDaedalus.data.math.Intersection EEdge(hxDaedalus.data.Edge edge)
	{
		return new hxDaedalus.data.math.Intersection(1, new java.lang.Object[]{edge});
	}
	
	
	public static hxDaedalus.data.math.Intersection EFace(hxDaedalus.data.Face face)
	{
		return new hxDaedalus.data.math.Intersection(2, new java.lang.Object[]{face});
	}
	
	
	public static final hxDaedalus.data.math.Intersection ENull = new hxDaedalus.data.math.Intersection(3, null);
	
	@Override public java.lang.String getTag()
	{
		return hxDaedalus.data.math.Intersection.__hx_constructs[this.index];
	}
	
	
}


