// Generated by Haxe 3.4.2
package hxDaedalus.data.math;

public class NodeData extends haxe.lang.HxObject
{
	public NodeData(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public NodeData()
	{
		hxDaedalus.data.math.NodeData.__hx_ctor_hxDaedalus_data_math_NodeData(this);
	}
	
	
	public static void __hx_ctor_hxDaedalus_data_math_NodeData(hxDaedalus.data.math.NodeData __hx_this)
	{
	}
	
	
	public int index;
	
	public hxDaedalus.data.math.Point2D point;
	
	@Override public double __hx_setField_f(java.lang.String field, double value, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case 100346066:
				{
					if (field.equals("index")) 
					{
						this.index = ((int) (value) );
						return value;
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_setField_f(field, value, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case 106845584:
				{
					if (field.equals("point")) 
					{
						this.point = ((hxDaedalus.data.math.Point2D) (value) );
						return value;
					}
					
					break;
				}
				
				
				case 100346066:
				{
					if (field.equals("index")) 
					{
						this.index = haxe.lang.Runtime.toInt(value);
						return value;
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case 106845584:
				{
					if (field.equals("point")) 
					{
						return this.point;
					}
					
					break;
				}
				
				
				case 100346066:
				{
					if (field.equals("index")) 
					{
						return this.index;
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public double __hx_getField_f(java.lang.String field, boolean throwErrors, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case 100346066:
				{
					if (field.equals("index")) 
					{
						return this.index;
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_getField_f(field, throwErrors, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		baseArr.push("point");
		baseArr.push("index");
		super.__hx_getFields(baseArr);
	}
	
	
}


