// Generated by Haxe 3.4.2
package hxDaedalus.data.math;

@SuppressWarnings(value={"rawtypes"})
public class Point2D extends haxe.lang.HxObject
{
	public Point2D(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Point2D(java.lang.Object x_, java.lang.Object y_)
	{
		hxDaedalus.data.math.Point2D.__hx_ctor_hxDaedalus_data_math_Point2D(this, x_, y_);
	}
	
	
	public static void __hx_ctor_hxDaedalus_data_math_Point2D(hxDaedalus.data.math.Point2D __hx_this, java.lang.Object x_, java.lang.Object y_)
	{
		double __temp_y_8 = ( (haxe.lang.Runtime.eq(y_, null)) ? (((double) (0) )) : haxe.lang.Runtime.toDouble(y_));
		__hx_this.x = ( (haxe.lang.Runtime.eq(x_, null)) ? (((double) (0) )) : haxe.lang.Runtime.toDouble(x_));
		__hx_this.y = __temp_y_8;
	}
	
	
	
	
	public double x;
	
	public double y;
	
	public void transform(hxDaedalus.data.math.Matrix2D matrix)
	{
		matrix.tranform(this);
	}
	
	
	public void setXY(double x_, double y_)
	{
		this.x = x_;
		this.y = y_;
	}
	
	
	public hxDaedalus.data.math.Point2D clone()
	{
		return new hxDaedalus.data.math.Point2D(this.x, this.y);
	}
	
	
	public void substract(hxDaedalus.data.math.Point2D p)
	{
		this.x -= p.x;
		this.y -= p.y;
	}
	
	
	public double get_length()
	{
		return java.lang.Math.sqrt(( ( this.x * this.x ) + ( this.y * this.y ) ));
	}
	
	
	public void normalize()
	{
		double norm = this.get_length();
		this.x /= norm;
		this.y /= norm;
	}
	
	
	public void scale(double s)
	{
		this.x *= s;
		this.y *= s;
	}
	
	
	public double distanceTo(hxDaedalus.data.math.Point2D p)
	{
		double diffX = ( this.x - p.x );
		double diffY = ( this.y - p.y );
		return java.lang.Math.sqrt(( ( diffX * diffX ) + ( diffY * diffY ) ));
	}
	
	
	@Override public double __hx_setField_f(java.lang.String field, double value, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case 121:
				{
					if (field.equals("y")) 
					{
						this.y = value;
						return value;
					}
					
					break;
				}
				
				
				case 120:
				{
					if (field.equals("x")) 
					{
						this.x = value;
						return value;
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_setField_f(field, value, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case 121:
				{
					if (field.equals("y")) 
					{
						this.y = haxe.lang.Runtime.toDouble(value);
						return value;
					}
					
					break;
				}
				
				
				case 120:
				{
					if (field.equals("x")) 
					{
						this.x = haxe.lang.Runtime.toDouble(value);
						return value;
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case -1963037360:
				{
					if (field.equals("distanceTo")) 
					{
						return new haxe.lang.Closure(this, "distanceTo");
					}
					
					break;
				}
				
				
				case -1106363674:
				{
					if (field.equals("length")) 
					{
						return this.get_length();
					}
					
					break;
				}
				
				
				case 109250890:
				{
					if (field.equals("scale")) 
					{
						return new haxe.lang.Closure(this, "scale");
					}
					
					break;
				}
				
				
				case 120:
				{
					if (field.equals("x")) 
					{
						return this.x;
					}
					
					break;
				}
				
				
				case 236609293:
				{
					if (field.equals("normalize")) 
					{
						return new haxe.lang.Closure(this, "normalize");
					}
					
					break;
				}
				
				
				case 121:
				{
					if (field.equals("y")) 
					{
						return this.y;
					}
					
					break;
				}
				
				
				case 974314479:
				{
					if (field.equals("get_length")) 
					{
						return new haxe.lang.Closure(this, "get_length");
					}
					
					break;
				}
				
				
				case 1052666732:
				{
					if (field.equals("transform")) 
					{
						return new haxe.lang.Closure(this, "transform");
					}
					
					break;
				}
				
				
				case 530534145:
				{
					if (field.equals("substract")) 
					{
						return new haxe.lang.Closure(this, "substract");
					}
					
					break;
				}
				
				
				case 109328099:
				{
					if (field.equals("setXY")) 
					{
						return new haxe.lang.Closure(this, "setXY");
					}
					
					break;
				}
				
				
				case 94756189:
				{
					if (field.equals("clone")) 
					{
						return new haxe.lang.Closure(this, "clone");
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public double __hx_getField_f(java.lang.String field, boolean throwErrors, boolean handleProperties)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case 121:
				{
					if (field.equals("y")) 
					{
						return this.y;
					}
					
					break;
				}
				
				
				case -1106363674:
				{
					if (field.equals("length")) 
					{
						return this.get_length();
					}
					
					break;
				}
				
				
				case 120:
				{
					if (field.equals("x")) 
					{
						return this.x;
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_getField_f(field, throwErrors, handleProperties);
			}
			else
			{
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, haxe.root.Array dynargs)
	{
		{
			boolean __temp_executeDef1 = true;
			switch (field.hashCode())
			{
				case -1963037360:
				{
					if (field.equals("distanceTo")) 
					{
						return this.distanceTo(((hxDaedalus.data.math.Point2D) (dynargs.__get(0)) ));
					}
					
					break;
				}
				
				
				case 1052666732:
				{
					if (field.equals("transform")) 
					{
						__temp_executeDef1 = false;
						this.transform(((hxDaedalus.data.math.Matrix2D) (dynargs.__get(0)) ));
					}
					
					break;
				}
				
				
				case 109250890:
				{
					if (field.equals("scale")) 
					{
						__temp_executeDef1 = false;
						this.scale(haxe.lang.Runtime.toDouble(dynargs.__get(0)));
					}
					
					break;
				}
				
				
				case 109328099:
				{
					if (field.equals("setXY")) 
					{
						__temp_executeDef1 = false;
						this.setXY(haxe.lang.Runtime.toDouble(dynargs.__get(0)), haxe.lang.Runtime.toDouble(dynargs.__get(1)));
					}
					
					break;
				}
				
				
				case 236609293:
				{
					if (field.equals("normalize")) 
					{
						__temp_executeDef1 = false;
						this.normalize();
					}
					
					break;
				}
				
				
				case 94756189:
				{
					if (field.equals("clone")) 
					{
						return this.clone();
					}
					
					break;
				}
				
				
				case 974314479:
				{
					if (field.equals("get_length")) 
					{
						return this.get_length();
					}
					
					break;
				}
				
				
				case 530534145:
				{
					if (field.equals("substract")) 
					{
						__temp_executeDef1 = false;
						this.substract(((hxDaedalus.data.math.Point2D) (dynargs.__get(0)) ));
					}
					
					break;
				}
				
				
			}
			
			if (__temp_executeDef1) 
			{
				return super.__hx_invokeField(field, dynargs);
			}
			
		}
		
		return null;
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		baseArr.push("y");
		baseArr.push("x");
		baseArr.push("length");
		super.__hx_getFields(baseArr);
	}
	
	
}


