// Generated by Haxe 3.4.2
package hxDaedalus.data.math;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Potrace extends haxe.lang.HxObject
{
	static
	{
		hxDaedalus.data.math.Potrace.MAX_INT = 2147483647;
		hxDaedalus.data.math.Potrace.maxDistance = 1;
	}
	
	public Potrace(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Potrace()
	{
		hxDaedalus.data.math.Potrace.__hx_ctor_hxDaedalus_data_math_Potrace(this);
	}
	
	
	public static void __hx_ctor_hxDaedalus_data_math_Potrace(hxDaedalus.data.math.Potrace __hx_this)
	{
	}
	
	
	public static int MAX_INT;
	
	public static double maxDistance;
	
//	public static haxe.root.Array<haxe.root.Array<java.lang.Object>> buildShapes(hxPixels._Pixels.PixelsData bmpData, hxPixels._Pixels.PixelsData debugBmp, wings.javaSwing.SimpleDrawingContext debugShape)
//	{
//		//line 22 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//		haxe.root.Array<haxe.root.Array<java.lang.Object>> shapes = new haxe.root.Array<haxe.root.Array<java.lang.Object>>();
//		//line 23 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//		haxe.ds.StringMap<java.lang.Object> dictPixelsDone = new haxe.ds.StringMap<java.lang.Object>();
//		//line 24 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//		{
//			//line 24 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//			int _g1 = 1;
//			//line 24 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//			int _g = ( bmpData.height - 1 );
//			//line 24 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//			while (( _g1 < _g ))
//			{
//				//line 24 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//				int row = _g1++;
//				//line 25 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//				{
//					//line 25 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//					int _g3 = 0;
//					//line 25 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//					int _g2 = ( bmpData.width - 1 );
//					//line 25 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//					while (( _g3 < _g2 ))
//					{
//						//line 25 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//						int col = _g3++;
//						//line 26 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//						if (( ((boolean) (( hxPixels._Pixels.Pixels_Impl_.getPixel(bmpData, col, row) == 16777215 )) ) && ((boolean) (( hxPixels._Pixels.Pixels_Impl_.getPixel(bmpData, ( col + 1 ), row) < 16777215 )) ) ))
//						{
//							//line 28 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//							if (( ! (haxe.lang.Runtime.toBool(((java.lang.Object) (dictPixelsDone.get(( ( ( col + 1 ) + "_" ) + row ))) ))) ))
//							{
//								//line 29 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//								shapes.push(hxDaedalus.data.math.Potrace.buildShape(bmpData, row, ( col + 1 ), dictPixelsDone, debugBmp, debugShape));
//							}
//
//						}
//
//					}
//
//				}
//
//			}
//
//		}
//
//		//line 35 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//		return shapes;
//	}
	
	
//	public static haxe.root.Array<java.lang.Object> buildShape(hxPixels._Pixels.PixelsData bmpData, int fromPixelRow, int fromPixelCol, haxe.ds.StringMap<java.lang.Object> dictPixelsDone, hxPixels._Pixels.PixelsData debugBmp, wings.javaSwing.SimpleDrawingContext debugShape)
//	{
//		//line 40 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//		double newX = ((double) (fromPixelCol) );
//		//line 41 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//		double newY = ((double) (fromPixelRow) );
//		//line 42 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//		haxe.root.Array<java.lang.Object> path = new haxe.root.Array<java.lang.Object>(new java.lang.Object[]{((java.lang.Object) (newX) ), ((java.lang.Object) (newY) )});
//		//line 43 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//		dictPixelsDone.set(( ( haxe.lang.Runtime.toString(newX) + "_" ) + haxe.lang.Runtime.toString(newY) ), true);
//		//line 45 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//		hxDaedalus.data.math.Point2D curDir = new hxDaedalus.data.math.Point2D(0, 1);
//		//line 46 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//		hxDaedalus.data.math.Point2D newDir = new hxDaedalus.data.math.Point2D(null, null);
//		//line 47 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//		int newPixelRow = 0;
//		//line 48 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//		int newPixelCol = 0;
//		//line 49 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//		int count = -1;
//		//line 50 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//		while (true)
//		{
//			//line 52 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//			if (( debugBmp != null ))
//			{
//				//line 54 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//				hxPixels._Pixels.Pixels_Impl_.setPixel32(debugBmp, fromPixelCol, fromPixelRow, -65536);
//			}
//
//			//line 59 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//			newPixelRow = ((int) (( ( fromPixelRow + curDir.x ) + curDir.y )) );
//			//line 60 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//			newPixelCol = ((int) (( ( fromPixelCol + curDir.x ) - curDir.y )) );
//			//line 63 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//			if (((boolean) (( hxPixels._Pixels.Pixels_Impl_.getPixel(bmpData, newPixelCol, newPixelRow) < 16777215 )) ))
//			{
//				//line 65 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//				newDir.x =  - (curDir.y) ;
//				//line 66 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//				newDir.y = curDir.x;
//			}
//			else
//			{
//				//line 69 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//				newPixelRow = ((int) (( fromPixelRow + curDir.y )) );
//				//line 70 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//				newPixelCol = ((int) (( fromPixelCol + curDir.x )) );
//				//line 72 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//				if (((boolean) (( hxPixels._Pixels.Pixels_Impl_.getPixel(bmpData, newPixelCol, newPixelRow) < 16777215 )) ))
//				{
//					//line 74 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//					newDir.x = curDir.x;
//					//line 75 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//					newDir.y = curDir.y;
//				}
//				else
//				{
//					//line 78 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//					newPixelRow = fromPixelRow;
//					//line 79 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//					newPixelCol = fromPixelCol;
//					//line 81 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//					newDir.x = curDir.y;
//					//line 82 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//					newDir.y =  - (curDir.x) ;
//				}
//
//			}
//
//			//line 85 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//			newX += curDir.x;
//			//line 86 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//			newY += curDir.y;
//			//line 88 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//			if (( ( newX == ((double) (haxe.lang.Runtime.toDouble(path.__get(0))) ) ) && ( newY == ((double) (haxe.lang.Runtime.toDouble(path.__get(1))) ) ) ))
//			{
//				//line 89 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//				break;
//			}
//			else
//			{
//				//line 91 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//				path.push(newX);
//				//line 92 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//				path.push(newY);
//				//line 93 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//				dictPixelsDone.set(( ( haxe.lang.Runtime.toString(newX) + "_" ) + haxe.lang.Runtime.toString(newY) ), true);
//				//line 94 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//				fromPixelRow = newPixelRow;
//				//line 95 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//				fromPixelCol = newPixelCol;
//				//line 96 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//				curDir.x = newDir.x;
//				//line 97 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//				curDir.y = newDir.y;
//			}
//
//			//line 100 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//			 -- count;
//			//line 101 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//			if (( count == 0 ))
//			{
//				//line 103 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//				break;
//			}
//
//		}
//
//		//line 108 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//		if (( debugShape != null ))
//		{
//			//line 110 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//			debugShape.lineStyle(0.5, 65280, null);
//			//line 111 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//			debugShape.moveTo(((double) (haxe.lang.Runtime.toDouble(path.__get(0))) ), ((double) (haxe.lang.Runtime.toDouble(path.__get(1))) ));
//			//line 112 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//			int i = 2;
//			//line 113 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//			while (( i < path.length ))
//			{
//				//line 114 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//				debugShape.lineTo(((double) (haxe.lang.Runtime.toDouble(path.__get(i))) ), ((double) (haxe.lang.Runtime.toDouble(path.__get(( i + 1 )))) ));
//				//line 115 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//				i += 2;
//			}
//
//			//line 117 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//			debugShape.lineTo(((double) (haxe.lang.Runtime.toDouble(path.__get(0))) ), ((double) (haxe.lang.Runtime.toDouble(path.__get(1))) ));
//		}
//
//		//line 120 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/math/Potrace.hx"
//		return path;
//	}
	
	
	public static hxDaedalus.data.graph.Graph buildGraph(haxe.root.Array<java.lang.Object> shape)
	{
		int i;
		hxDaedalus.data.graph.Graph graph = new hxDaedalus.data.graph.Graph();
		hxDaedalus.data.graph.GraphNode node;
		i = 0;
		while (( i < shape.length ))
		{
			node = graph.insertNode();
			node.set_data(new hxDaedalus.data.math.NodeData());
			node.get_data().index = i;
			double shape1 = haxe.lang.Runtime.toDouble(shape.__get(i));
			double shape2 = haxe.lang.Runtime.toDouble(shape.__get(( i + 1 )));
			node.get_data().point = new hxDaedalus.data.math.Point2D(shape1, shape2);
			i += 2;
		}
		
		hxDaedalus.data.graph.GraphNode node1;
		hxDaedalus.data.graph.GraphNode node2;
		hxDaedalus.data.graph.GraphNode subNode;
		double distSqrd;
		double sumDistSqrd;
		int count;
		boolean isValid;
		hxDaedalus.data.graph.GraphEdge edge;
		hxDaedalus.data.math.EdgeData edgeData;
		node1 = graph.get_node();
		while (( node1 != null ))
		{
			if (( node1.get_next() != null )) 
			{
				node2 = node1.get_next();
			}
			else
			{
				node2 = graph.get_node();
			}
			
			while (( node2 != node1 ))
			{
				isValid = true;
				if (( node1.get_next() != null )) 
				{
					subNode = node1.get_next();
				}
				else
				{
					subNode = graph.get_node();
				}
				
				count = 2;
				sumDistSqrd = 0;
				while (( subNode != node2 ))
				{
					distSqrd = hxDaedalus.data.math.Geom2D.distanceSquaredPointToSegment(subNode.get_data().point.x, subNode.get_data().point.y, node1.get_data().point.x, node1.get_data().point.y, node2.get_data().point.x, node2.get_data().point.y);
					if (( distSqrd < 0 )) 
					{
						distSqrd = 0;
					}
					
					if (( distSqrd >= hxDaedalus.data.math.Potrace.maxDistance )) 
					{
						isValid = false;
						break;
					}
					
					 ++ count;
					sumDistSqrd += distSqrd;
					if (( subNode.get_next() != null )) 
					{
						subNode = subNode.get_next();
					}
					else
					{
						subNode = graph.get_node();
					}
					
				}
				
				if ( ! (isValid) ) 
				{
					break;
				}
				
				edge = graph.insertEdge(node1, node2);
				edgeData = new hxDaedalus.data.math.EdgeData();
				edgeData.sumDistancesSquared = sumDistSqrd;
				edgeData.length = node1.get_data().point.distanceTo(node2.get_data().point);
				edgeData.nodesCount = count;
				edge.set_data(edgeData);
				if (( node2.get_next() != null )) 
				{
					node2 = node2.get_next();
				}
				else
				{
					node2 = graph.get_node();
				}
				
			}
			
			node1 = node1.get_next();
		}
		
		return graph;
	}
	
	
	public static haxe.root.Array<java.lang.Object> buildPolygon(hxDaedalus.data.graph.Graph graph, java.lang.Object debugShape)
	{
		haxe.root.Array<java.lang.Object> polygon = new haxe.root.Array<java.lang.Object>();
		hxDaedalus.data.graph.GraphNode currNode;
		int minNodeIndex = 2147483647;
		hxDaedalus.data.graph.GraphEdge edge;
		double score;
		double higherScore;
		hxDaedalus.data.graph.GraphEdge lowerScoreEdge = null;
		currNode = graph.get_node();
		while (( currNode.get_data().index < minNodeIndex ))
		{
			minNodeIndex = currNode.get_data().index;
			polygon.push(currNode.get_data().point.x);
			polygon.push(currNode.get_data().point.y);
			higherScore = 0;
			edge = currNode.get_outgoingEdge();
			while (( edge != null ))
			{
				score = ( edge.get_data().nodesCount - ( edge.get_data().length * java.lang.Math.sqrt(( edge.get_data().sumDistancesSquared / edge.get_data().nodesCount )) ) );
				if (( score > higherScore )) 
				{
					higherScore = score;
					lowerScoreEdge = edge;
				}
				
				edge = edge.get_rotNextEdge();
			}
			
			currNode = lowerScoreEdge.get_destinationNode();
		}
		
		if (( hxDaedalus.data.math.Geom2D.getDirection(haxe.lang.Runtime.toDouble(polygon.__get(( polygon.length - 2 ))), haxe.lang.Runtime.toDouble(polygon.__get(( polygon.length - 1 ))), haxe.lang.Runtime.toDouble(polygon.__get(0)), haxe.lang.Runtime.toDouble(polygon.__get(1)), haxe.lang.Runtime.toDouble(polygon.__get(2)), haxe.lang.Runtime.toDouble(polygon.__get(3))) == 0 ))
		{
			polygon.shift();
			polygon.shift();
		}
		
		if (( ! (( debugShape == null )) )) 
		{
			haxe.lang.Runtime.callField(haxe.lang.Runtime.getField(debugShape, "graphics", true), "lineStyle", new haxe.root.Array(new java.lang.Object[]{0.5, 255}));
			haxe.lang.Runtime.callField(haxe.lang.Runtime.getField(debugShape, "graphics", true), "moveTo", new haxe.root.Array(new java.lang.Object[]{haxe.lang.Runtime.toDouble(polygon.__get(0)), haxe.lang.Runtime.toDouble(polygon.__get(1))}));
			int i = 2;
			while (( i < polygon.length ))
			{
				haxe.lang.Runtime.callField(haxe.lang.Runtime.getField(debugShape, "graphics", true), "lineTo", new haxe.root.Array(new java.lang.Object[]{haxe.lang.Runtime.toDouble(polygon.__get(i)), haxe.lang.Runtime.toDouble(polygon.__get(( i + 1 )))}));
				i += 2;
			}
			
			haxe.lang.Runtime.callField(haxe.lang.Runtime.getField(debugShape, "graphics", true), "lineTo", new haxe.root.Array(new java.lang.Object[]{haxe.lang.Runtime.toDouble(polygon.__get(0)), haxe.lang.Runtime.toDouble(polygon.__get(1))}));
		}
		
		return polygon;
	}
	
	
}


